README.md

I was trying to reproduce the workflow to understand how it can be done from scratch.
I did cargo build first and then flutter_rust_bridge_codegen. Of course I got the error - undefined symbol: store_dart_post_cobject.
Finally I realized that the order is the other way around. The codegen should be done first and then cargo build (or make) so that the rust compiler can find the generated rust file and includes it to be a part of the end result.
I know this is solely my mistake, but I want to help others like me :eyeglasses:

Update README for trouble shooting.

---

CHANGELOG.md
frb_codegen/src/commands.rs
frb_codegen/src/config.rs
frb_codegen/src/main.rs

This works now
```
flutter_rust_bridge_codegen --rust-input frb_example/with_flutter/rust/src/api.rs --dart-output frb_example/with_flutter/lib/bridge_generated.dart --c-output frb_example/with_flutter/ios/Runner/bridge_generated.h --llvm-compiler-opts=-I/usr/lib/clang/13.0.0/include/
```

Add llvm-compiler-opts as command-line argument

---

CHANGELOG.md
frb_codegen/src/main.rs

This patch adds `fs::create_dir_all` calls to `frb_codegen/src/main.rs` to ensure directories exist before trying to write files in them.
Currently, running `frb_codegen` with `--rust-output folder_does_not_exist/code.rs` causes the program to exit with a filesystem error (tested on Windows 10).
I'm creating a bindgen script, in which I run `frb_codegen` and tell it to write my generated dart code to to a folder called `generated`. I'd like to gitignore my auto-generated code. However, my `generated` folder only contains auto-generated files, which means the folder itself isn't created when the repo is checked out for the first time. As a result, my bindgen script encounters the error above. I can create the folder using my shell script, but I think it's reasonable for `frb_codegen` to …

When writing files in frb_codegen, create directories if they don't exist

---

frb_codegen/src/generator_dart.rs
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/with_flutter/lib/bridge_generated.dart

Rename ffi call port argument

---

frb_codegen/src/commands.rs
frb_codegen/src/config.rs
frb_codegen/src/main.rs
justfile

Partial fix #323
A few changes in the internal API:
- execute_command now takes a binary, a list of arguments and returns Output marked with `#[must_use]`
- Common failures are enumerated and handled, otherwise panic
- Changed llvm-path to take multiple parameters, and add some default search paths for LLVM

Refactor command module

---

frb_codegen/src/api_types.rs
frb_codegen/src/generator_rust.rs
frb_codegen/src/parser.rs
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/with_flutter/rust/src/api.rs
frb_example/with_flutter/rust/src/bridge_generated.rs

Fixes #332
I implemented this by wrapping the returned type in `bridge_generated.rs` with `Ok(...)` whenever there's a non-`Result<_>` return type. So under the hood, the top-level return type is still always a special-cased `Result<_>`.
The _ideal_ solution would probably be to add support for parsing `Result<_>` as a type and giving it a generalized Dart<->Rust representation, so it could be supported inside nested structures. In the meantime this is a nice convenience for bridging infallible functions.
As an aside: I'm not really sure what `StreamSink` is used for, so I didn't touch anything related to it. `Result<_>` still seems to be required there as a return type, although there's also no error when it's not specified.

Support bridging functions with return types other than `Result<_>`

---

frb_codegen/src/ir/func.rs
frb_codegen/src/parser/mod.rs
frb_codegen/src/parser/ty.rs

Closes #340 
This is already a good number of changes to start with, but there's a few followups that might be useful here, including:
- Better error handling. Right now everything either panics or returns an `Option` as an output type. `Result`s would be more friendly to work with.
- Unifying the `IrFunc` model with `IrFuncOutput` and `IrFuncArg`. The way I've implemented it, just the type from each `IrFuncArg` and `IrFuncOutput` is extracted and stored in `IrFunc` along with the `fallible` and `mode` information. This would also be a good opportunity to forbid more combinations in function signatures, like `StreamSink` along with another return type.
I tried to keep functionality as similar as possible; all the existing test cases are interpreted without any changes. There is one …

Avoid converting syn types to strings before parsing

---

frb_codegen/src/source_graph.rs

This patch should fix the issues described in #360. It disables import parsing, since the code itself is unfinished and the result isn't being used.

Speculative fix for #360

---

frb_codegen/src/commands.rs
frb_codegen/src/config.rs
frb_codegen/src/generator/dart/mod.rs
frb_codegen/src/main.rs
frb_example/pure_dart/dart/pubspec.lock
justfile

Resolves #344.
- Added `--verbose` flag
- Added `--dart-root` flag to specify root of Dart library, by default inferred
- Runs `dart run build_runner build` at the Dart root if freezed code is detected, also lint generated files
- Added `--no-build-runner` to skip running build_runner
- Fixed "bridge_generated.freezed.dart" being hardcoded
- Allow specifying multiple `--c-output`

CLI improvements

---

frb_codegen/src/config.rs

Mitigates the issue described in [this comment](https://github.com/fzyzcjy/flutter_rust_bridge/issues/407#issuecomment-1104671598).

Add default LLVM installation path for Windows

---

frb_codegen/src/generator/dart/ty_struct.rs
frb_codegen/src/ir/field.rs
frb_codegen/src/markers.rs
frb_codegen/src/parser/mod.rs
frb_codegen/src/parser/ty.rs
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart
frb_example/pure_dart/dart/lib/main.dart
frb_macros/src/lib.rs

Use the #[frb(non_final)] attribute on a field in a Rust struct to
make the corresponding field in the Dart struct non-final.

Non-final fields in Dart structs.

---

book/src/template/setup_others.md
book/src/troubleshooting.md

Since the release of Flutter 3, Apple silicon should be fully supported and the specific sections should no longer be needed.

Remove M1 specific sections in the book

---

book/src/integrate/ios_headers.md

For context, see https://github.com/fzyzcjy/flutter_rust_bridge/issues/496.

Update iOS headers section of book with code that ensures symbols do not get stripped

---

book/src/feature/stream.md

Now includes section about rerunning `flutter_rust_bridge_codegen` to generate `IntoDart` trait implementation

Updated stream chapter in book

---

.github/workflows/ci.yaml
.github/workflows/post_release.yaml
frb_codegen/src/generator/dart/ty_primitive.rs
frb_codegen/src/ir/ty_primitive.rs
frb_dart/lib/src/basic.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart
frb_example/with_flutter/lib/bridge_generated.dart

Based on [this comment](https://github.com/fzyzcjy/flutter_rust_bridge/issues/478#issuecomment-1168648564).
This fixes the syntax error and allows my project to build with `ffigen` >= 6.0. I haven't tested thoroughly and I don't fully understand what's going on, so I'm relying on CI to validate it. If CI doesn't pass then I'll dig into it more.
This is a breaking change, as I expect this PR to cause `flutter_rust_bridge` to break with `ffigen` < 6.0. `ffigen` can be upgraded by running `dart pub global activate ffigen`.
Resolves #478 and resolves #512.

Speculative fix for `store_dart_post_cobject` signature mismatch with `ffigen` >= 6.0

---

book/src/feature.md
book/src/template/generate_multiple_blocks.md

Mention the new  example in Section `3.Features`.
Add a new doc for detailed explanation on why and how to generate Api within multiple blocks(files).
https://github.com/fzyzcjy/flutter_rust_bridge/pull/516
https://github.com/fzyzcjy/flutter_rust_bridge/pull/527
https://github.com/fzyzcjy/flutter_rust_bridge/issues/511

Doc for generation with multiple blocks of Api

---

.github/workflows/ci.yaml
.github/workflows/post_release.yaml

fix #611 : remove macos-10.15 image from ci and post release matrices
Remark for PR creator: If the PR is submitted but the owner (fzyzcjy) does not reply for a few days, maybe he just did not see it, so please ping him.

:fire: deprecate macos 10.15

---

frb_codegen/src/source_graph.rs
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart
frb_example/pure_dart/dart/lib/main.dart
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/lib.rs
frb_example/pure_dart/rust/src/new_module_system.rs
frb_example/pure_dart/rust/src/new_module_system/sub_module.rs
frb_example/pure_dart/rust/src/old_module_system/mod.rs
frb_example/pure_dart/rust/src/old_module_system/sub_module.rs

There are warnings "Skipping unresolvable module XXX" when we use the newer rust module system, eg:
```
some_module.rs
some_module/sub_module.rs
```
The cause is that source_graph assume that there must be a `mod.rs` in the module folder, which is not true sometimes.
This PR fix that.

fix "Skipping unresolvable module" by align latest

---

book/src/feature/sync_dart.md
frb_codegen/src/generator/dart/mod.rs
frb_codegen/src/generator/dart/ty.rs
frb_codegen/src/generator/dart/ty_delegate.rs
frb_codegen/src/generator/dart/ty_sync_return.rs
frb_codegen/src/generator/rust/mod.rs
frb_codegen/src/generator/rust/ty.rs
frb_codegen/src/generator/rust/ty_delegate.rs
frb_codegen/src/generator/rust/ty_sync_return.rs
frb_codegen/src/ir/mod.rs
frb_codegen/src/ir/ty.rs
frb_codegen/src/ir/ty_delegate.rs
frb_codegen/src/ir/ty_sync_return.rs
frb_codegen/src/parser/mod.rs
frb_codegen/src/parser/ty.rs
frb_dart/lib/src/basic.dart
frb_dart/lib/src/helpers.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/main.dart
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_rust/src/handler.rs
frb_rust/src/lib.rs
frb_rust/src/support.rs

If there are any problems with my code or design, please let me know😊😊
* Added a new IR type: IrTypeSyncReturn.
* SyncReturn now supports String, Vec\<u8\> and most of the primitive types(`bool`, `u8`, `u16`, `u32`, `u64`, `i8`, `i16`, `i32`, `i64`, `f32`, `f64`).
* Removed SyncReturnVecU8 from IrTypeDelegate since SyncReturn now has an individual IR.
* Added `parseSuccessData` for `FlutterRustBridgeSyncTask`, it does the type conversion for Dart.
* Implemented `From` trait for `WireSyncReturnStruct`, it does the type conversion for Rust.
* Added generic type constraint for SyncReturn, now if users are trying to use an unsupported type for SyncReturn, they will immediately get a compiler error.

Refactor and enhance `SyncReturn` to support more types

---

frb_dart/lib/src/basic.dart

In `frb_dart/lib/src/basic.dart`, the method `free_WireSyncReturnStruct` should be invoked **after** the buffer being consumed (either parsed as success data or as error string), in case of accessing deallocated memory.

Fix: WireSyncReturnStruct should be freed after buffer being consumed

---

.github/workflows/gh-pages.yaml
book/book.toml
book/src/SUMMARY.md
book/src/article/generate_multiple_files.md
book/src/feature/lang_chrono.md
book/src/feature/lang_simple.md
book/src/feature/lang_uuid.md
book/src/integrate/deps.md
book/src/template/generate.md

A couple of links are broken in the docs, see #731.
It fixes them and add [mdbook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck) to the CI.

Fix broken links in book

---

.github/workflows/post_release.yaml

Feature flags are missing in CI when running `frb_codegen` in `post-release` CI workflow.
I haven't checked yet if there are other places where it's missing.

Fix post-release

---

.github/workflows/post_release.yaml

Please don't revert just yet.
This fixes the issue in latest `post-release` flow. Sorry I confused the binary with the crate.

:ambulance: fix post-release

---

.github/workflows/ci.yaml
frb_dart/bin/serve.dart
frb_example/pure_dart/dart/lib/main.dart

Prevents unit tests failing in release mode. Fixes #752

Do not compare `runtimeType` string reprs in test

---

book/src/troubleshooting.md

Add a note to Troubleshooting about an annoying issue with symbols being stripped only when deploying an iOS app.

Add note about symbol stripping on iOS

---

frb_codegen/src/tools.rs
frb_example/pure_dart/dart/pubspec.lock
frb_example/pure_dart/dart/pubspec.yaml
frb_example/pure_dart/dart/pubspec.yaml.release
frb_example/pure_dart_multi/dart/pubspec.lock
frb_example/pure_dart_multi/dart/pubspec.yaml
frb_example/pure_dart_multi/dart/pubspec.yaml.release
frb_example/with_flutter/pubspec.lock
frb_example/with_flutter/pubspec.yaml
frb_example/with_flutter/pubspec.yaml.release

bump constraint on ffigen

---

frb_codegen/src/tools.rs

Fixes https://github.com/fzyzcjy/flutter_rust_bridge/issues/826. As part of this I also make it print the errors in the failure case, so it's easier to see what's wrong with your spec.
I tested this against my own repo using the repro described in the above issue and the parsing step fixed it. I haven't fully tested the end to end flow though because I'm getting a different, likely unrelated issue related to llvm dynamic libraries.
- I removed the version constraint for one of the more innocuous dependencies.

Fix parsing of packages in pubspec.yaml that have no explicit version specification

---

book/src/integrate/android_tasks.md
book/src/template/setup_android.md

Some details are added for using Android with frb.
Some syntax is fixed for the corresponding articles.
https://github.com/fzyzcjy/flutter_rust_bridge/issues/788
When testing with the latest Android NDK((Side by side) 25.1.8937393), there is no need to do any workaround as stated in the article [Android setup](https://cjycode.com/flutter_rust_bridge/template/setup_android.html#android-setup) for NDK lower than v22.

Update documents for Android Settings

---

book/src/template/setup_android.md

As can be seen at https://developer.android.com/studio/command-line/variables, the only modern variables are `ANDROID_HOME` and `ANDROID_USER_HOME`, the former of which I think is applicable in this case.
I removed the issue checklist as I don't think it's required for a doc change.

Migrate to modern Android environment variables

---

book/src/set_up_from_scratch.md
book/src/troubleshooting.md
frb_dart/pubspec.yaml
frb_example/pure_dart/dart/pubspec.yaml.release
frb_example/pure_dart_multi/dart/pubspec.yaml
frb_example/pure_dart_multi/dart/pubspec.yaml.release
frb_example/with_flutter/pubspec.yaml
frb_example/with_flutter/pubspec.yaml.release

Follows up on #882 more precisely [@fzyzcjy's suggestion](https://github.com/fzyzcjy/flutter_rust_bridge/pull/882#issuecomment-1355844249)
This bump is motivated by the use of [constructor tearoffs](https://medium.com/dartlang/dart-2-15-7e7a598e508a#9c16): passing constructor as a regular function.
It shouldn't be a major issue for FRB users considering that ffigen currenttly required sdk is 2.17.

Bump Dart SDK to 2.15

---

frb_codegen/src/generator/rust/mod.rs
frb_codegen/src/generator/rust/ty.rs
frb_codegen/src/generator/rust/ty_boxed.rs
frb_codegen/src/generator/rust/ty_dart_opaque.rs
frb_codegen/src/generator/rust/ty_delegate.rs
frb_codegen/src/generator/rust/ty_enum.rs
frb_codegen/src/generator/rust/ty_general_list.rs
frb_codegen/src/generator/rust/ty_optional.rs
frb_codegen/src/generator/rust/ty_rust_opaque.rs
frb_codegen/src/generator/rust/ty_struct.rs
frb_example/pure_dart/dart/lib/bridge_definitions.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.io.dart
frb_example/pure_dart/dart/lib/bridge_generated.web.dart
frb_example/pure_dart/rust/external/src/lib.rs
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.io.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/bridge_generated.web.rs

Fix mirroring to support `Result` return type and `Option<T>` field

---

frb_codegen/src/config.rs
frb_codegen/src/lib.rs
frb_codegen/src/utils.rs

Fixes #911.
New output when rust input file does not exist:
```
Error: Failed to read rust input file "[...]/flutter_rust_bridge/frb_example/with_flutter/rust/api.rs"
Caused by:
No such file or directory (os error 2)
```
Feel free to suggest a different way of reporting the error.

Return error when rust input file cannot be read

---

book/src/library/melos.md

This is the only supported behaviour now - see https://github.com/invertase/melos/pull/430 .

Remove reference to `usePubspecOverrides`

---

book/src/library/platform_setup/ios_and_macos.md

Hi, I just noticed that in release mode the static library was getting stripped for iOS and macOS.
I can't quite explain why, but this exact change with separating a method from a variable seems to do the trick. Note: setting the variable directly to the result of `dummy_...` does *not* work.

fix: force library bundling for iOS and macOS in release mode

---

README.md
frb_codegen/src/commands.rs
frb_dart/pubspec.yaml
frb_rust/src/ffi/web.rs

This pr modified code a little to fix errors posted after running `just precommit` locally and online Github CI test.
By the way, the [lint ](https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc)posted for `get_dart_object` and `drop_dart_object` may need a detailed description, it'd better be written by the one who wrote these methods.

Fix syntax issues warned by lint

---

.github/workflows/code_generator.yml
.github/workflows/post_release.yaml
frb_rust/src/lib.rs

This PR fixes #935 the limitation of SyncReturn IntoDart as this limitation duplicates the limitation in the generated code and may cause errors on first generation.
additionally `ffigen 7.2.4` now generates `UIntPtr` instead of `UnsignedLongLong` (ci fix)

fix `SyncReturn` restrictions and update CI

---

book/src/integrate/ios_headers.md

Everything worked fine with `flutter run` and `flutter run --release`. But when I was distributing my app through TestFlight symbols suddenly disappeared and I was stuck with infamous *"Failed to lookup symbol 'store_dart_post_cobject'"* error.
I had to modify the setting for the app to start working on iOS.
Btw, thank you for this project!

Specify how to prevent Xcode from stripping symbols in iOS

---

.github/workflows/ci.yaml
Cargo.lock
README.md
book/src/contributing/design.md
frb_codegen/src/generator/dart/ty_boxed.rs
frb_codegen/src/generator/dart/ty_optional.rs
frb_codegen/src/generator/rust/ty_boxed.rs
frb_codegen/src/generator/rust/ty_delegate.rs
frb_codegen/src/generator/rust/ty_optional.rs
frb_codegen/src/ir/ty.rs
frb_codegen/src/ir/ty_boxed.rs
frb_codegen/src/ir/ty_enum.rs
frb_codegen/src/ir/ty_optional.rs
frb_codegen/src/parser/ty.rs
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.web.dart
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.io.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/bridge_generated.web.rs
frb_example/pure_dart_multi/rust/src/lib.rs
justfile

- Refactors `EnumRef` to make `Option<FieldlessEnum>` work
- (Potentially breaking) `Box<primitive>` and `Option<Box<primitive>>` on WASM no longer allocates a Box, but receives a (nullable) value directly from Dart. Makes the implementation cleaner.
Closes #828.

Refactors for `Boxed` and `Option`

---

book/src/integrate/deps.md
book/src/tutorial_with_flutter.md

Fixes  source of #1011 and similar https://github.com/fzyzcjy/flutter_rust_bridge/issues?q=%27stdbool.h%27+file+not+found
Have **not** changed source code, only add info in docs. So, skip code test part

add setup steps in tutorial

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/post_release.yaml
justfile

This PR fixes side-effects caused by https://github.com/fzyzcjy/flutter_rust_bridge/pull/1039. Specifically, Post-Release Valgrind test is throwing errors and some justfile commands are broken.
- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory, You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce erorrs as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping …

Fix workflows

---

book/src/feature/sync_dart.md

Add a guide about threads in `sync_dart.md` docs. This behavior was inspected in https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1028.

Add a guide about threads in `sync_dart.md` docs

---

book/src/library/dart_only.md

There were a few issues with the old library initialization script:
1. Generated C output could only go to one file, but multiple were specified. This was broken sometime after the docs were made.
2. The Dart and Rust FRB versions might mismatch. This commit pins an exact version of FRB in Dart/Rust so no issues will occur.

docs: fix broken library initialization script

---

book/src/template/setup_android.md

At least for me, using `NDK (Obsolete)` gave me the error
```
error occurred: Failed to find tool. Is `/home/voklen/programs/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar` installed?
```
But after instead using `NDK (Side by side)` version `22.1.7171670` now works and runs on my device
OS: Arch Linux
Android device: Fairphone 4 running LineageOS
Changed NDK install instructions

Clarify NDK setup for Android

---

frb_codegen/src/generator/dart/ty_struct.rs
frb_codegen/src/generator/rust/ty_struct.rs
frb_example/pure_dart/dart/lib/bridge_definitions.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.io.dart
frb_example/pure_dart/dart/lib/bridge_generated.web.dart
frb_example/pure_dart/dart/lib/main.dart
frb_example/pure_dart/dart/pubspec.lock
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.io.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/bridge_generated.web.rs
frb_example/pure_dart_multi/dart/pubspec.lock
frb_example/with_flutter/pubspec.lock
frb_example/with_flutter/rust/src/bridge_generated.io.rs

Allows the use of nested `struct`s or `enum`s in `struct`s without wrapping the inner struct with `Box`.
E. g. `struct A { b: B }` now also works in addition to `struct A { b: Box<B> }` (which had to be used before).
This is related to some of the problems encountered in #525, #548, though there might be [more related issues](https://github.com/fzyzcjy/flutter_rust_bridge/issues/525#issuecomment-1223580725).
So far this seems to be working with nested `struct`s and simple `enum`s (without associated data) in `struct`s,
though I haven't really looked into `enum`s with associated data (e. g. `enum B { A, B { s: String, i: i64 }, C(C) }`), yet.
TODO: update [docs](https://cjycode.com/flutter_rust_bridge/feature/lang_struct.html)
* New contributors will be blocked by GitHub from running CI, …

nested `struct`s and `enum`s in `struct`s without `Box`

---

book/src/SUMMARY.md
book/src/template/setup_android.md
book/src/tutorial/alternative_ndk.md
book/src/tutorial/setup_android.md
book/src/tutorial_with_flutter.md

When I was trying to run the example project it worked perfectly on Linux but for Android I had to first setup the NDK. I've therefore put that bit in the initial tutorial for running for Android and then linked to it from the template Android setup. I've also move the `Alternative NDK setup` into a separate file to make the main one more focused.

Reorder Android setup docs

---

book/src/tutorial/alternative_ndk.md
book/src/tutorial/setup_android.md

This PR adds documentation for Rust versions 1.68 and above with the latest Android NDK.
Closes #1069

Add documentation for Rust versions 1.68 and above with the latest Android NDK

---

book/src/feature/lang_default.md
frb_codegen/src/generator/dart/ty_struct.rs
frb_example/pure_dart/dart/lib/bridge_definitions.dart
frb_example/pure_dart/dart/lib/bridge_definitions.freezed.dart
frb_example/pure_dart/rust/src/api.rs
justfile

Continued from #1095.
Also fixes CI failing from incorrect assumption regarding lints.

fix: default on freezed structs not applied

---

book/src/feature/build_rs.md
frb_codegen/src/main.rs
justfile

For #1105, this PR adds `#[test]`s to `frb_codegen/main.rs` to generate, build, and run pure_dart and pure_dart_multi.
It may be desirable to remove `frb_example/pure_dart/rust/build.rs` and `frb_example/pure_dart_multi/rust/build.rs` entirely, to prevent divergence, leverage Rust's test capabilities, and to avoid confusion caused by #1105 in the first place, but I have left them there to keep changes to a minimum.
I also experimented with making `pure_dart` and `pure_dart_multi` independent, not part of the workspace, but I ran into problems with Rust failing to resolve `IntoDart` implementations for Vecs of `chrono` types.
- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use …

Add tests to gen, build, run pure_dart(_multi)

---

book/src/command_line.md
book/src/feature/build_rs.md
book/src/troubleshooting.md
frb_codegen/src/config.rs
frb_example/with_flutter/README.md

- Closes #1121
- Closes #1120
- feat: look in `pubspec.yaml` for a flutter_rust_bridge config
- docs: general improvements

Fixes for `serde-yml`

---

book/src/feature/lang_vec.md

remove extra `it` in `lang_vec.md`.

docs: minor wording fix in lang_vec

---

frb_codegen/src/generator/dart/ty_struct.rs
frb_example/pure_dart/dart/lib/bridge_definitions.dart
frb_example/pure_dart/dart/lib/bridge_definitions.freezed.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.io.dart
frb_example/pure_dart/dart/lib/bridge_generated.web.dart
frb_example/pure_dart/dart/lib/main.dart
frb_example/pure_dart/rust/c_output_path/c_output.h
frb_example/pure_dart/rust/c_output_path_extra/c_output.h
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.io.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/bridge_generated.web.rs

Fixed generating Dart structs with freezed + methods

---

frb_codegen/src/config/opts_parser.rs
frb_codegen/src/config/raw_opts_parser.rs

This PR fixes a small issue preventing `frb_codegen` from building with `--no-default-features` (without the `serde` feature enabled).
```rust
$ cargo check -p flutter_rust_bridge_codegen --no-default-features
Checking flutter_rust_bridge_codegen v1.75.0
warning: unused import: `anyhow::Context`
--> frb_codegen/src/config/raw_opts_parser.rs:2:5
|
2 | use anyhow::Context;
|     ^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `clap::Parser`
--> frb_codegen/src/config/raw_opts_parser.rs:3:5
|
3 | use clap::Parser;
|     ^^^^^^^^^^^^
warning: unused import: `std::fs`
--> frb_codegen/src/config/raw_opts_parser.rs:4:5
|
4 | use std::fs;
|     ^^^^^^^
error[E0560]: struct `RawOpts` has no field named `dump`
--> frb_codegen/src/config/opts_parser.rs:278:9 …
```

fix: fix compile error when building `frb_codegen` w/o `serde` feature

---

frb_codegen/src/config/opts_parser.rs

Fixes #1191
Warns the user if a Rust input they provided contains "lib.rs". When generating code from a `lib.rs`, the `use` statement in `bridge_generated.rs` is incorrect because the convention is not followed.
- If fzyzcjy does not reply for a few days, maybe he just did not see …

Warn user about using `lib.rs` as a Rust input.

---

frb_codegen/src/config/opts.rs
frb_codegen/src/generator/dart/mod.rs
frb_codegen/src/generator/dart/ty_rust_opaque.rs
frb_codegen/src/generator/dart/ty_struct.rs
frb_example/pure_dart/dart/lib/ffi.io.dart
frb_example/pure_dart/dart/lib/ffi.web.dart

Fix code generated for Rust opaques when `--no-use-bridge-in-method` is active (referencing a non-existent `bridge`)

fix: Bridge access for Rust opaques

---

book/src/integrate/ios_headers.md
book/src/integrate/ios_proj.md

This PR adds crucial information about macOS integration. The docs were almost there, but few steps were missing to make the integration work.
As described in #870, many people seemed to be using `staticlib` for macOS apps, not `dylib`. This was because dynamic libraries were not being included in the `Frameworks` folder of the macOS app package and thus the executable was not able to find the `dylib` file.
This PR adds documentation about how to include the `dylib` file and locate it from the executable. The solution was inspired from #870 and https://crates.io/crates/cargo-xcode docs. I confirmed on my macbook that it works.
- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use …

Add crucial info on macOS integration in docs

---

Cargo.lock
Cargo.toml

[I made an additional PR](https://github.com/sunshine-protocol/allo-isolate/pull/41) at the `allo-isolate` repository. I accidentally left the outdated code in the last commit. I will update the version number of `allo-isolate` if the new PR is accepted.
- If fzyzcjy does not reply …

Fix on `zero-copy` cargo feature

---

Cargo.toml
book/src/help.txt
frb_codegen/Cargo.toml
frb_codegen/src/commands.rs
frb_codegen/src/commands/error.rs
frb_codegen/src/config/error.rs
frb_codegen/src/config/mod.rs
frb_codegen/src/config/opts.rs
frb_codegen/src/config/opts_parser.rs
frb_codegen/src/config/raw_opts.rs
frb_codegen/src/config/refine_c_output.rs
frb_codegen/src/dump.rs
frb_codegen/src/entrypoint/dart.rs
frb_codegen/src/error.rs
frb_codegen/src/lib.rs
frb_codegen/src/main.rs
frb_codegen/src/others.rs
frb_codegen/src/parser/error.rs
frb_codegen/src/parser/mod.rs
frb_codegen/src/parser/source_graph.rs
frb_codegen/src/parser/ty.rs
frb_codegen/src/utils/command_runner.rs
frb_codegen/src/utils/dart_repository/dart_repo.rs
frb_codegen/src/utils/misc.rs
frb_example/pure_dart/dart/pubspec.yaml
frb_example/pure_dart/dart/pubspec.yaml.release

- Replace `anyhow::Error` with canonical error listings for library functions
- Each module tries to manage its own error listing, rather than a single union of errors
- Allow `Err(anyhow!(..))?` as the new adhoc error syntax
- Aim to reduce dependency on panicking as an error handling mechanism
- New flag `--keep-going` to delay error reporting to after codegen
- Use `anyhow::Context` where possible to make code concise and preserve backtraces
IR functions and methods are not included and should/may come in a separate PR.
The following public APIs have been changed:
- `ensure_tools_available` has opaque error type
- `dump::dump_multi` has opaque error type
- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your …

feat: reinforce error handling, reduce panics

---

frb_codegen/src/generator/dart/mod.rs
frb_example/pure_dart/dart/lib/bridge_definitions.dart
frb_example/pure_dart/dart/lib/bridge_definitions.freezed.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.io.dart
frb_example/pure_dart/dart/lib/bridge_generated.web.dart
frb_example/pure_dart/dart/lib/main.dart
frb_example/pure_dart/rust/c_output_path/c_output.h
frb_example/pure_dart/rust/c_output_path_extra/c_output.h
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.io.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/bridge_generated.web.rs

Check whether the children type of `SyncReturn` contains a `freezed` dart metadata in the frb macro.

fix: sync return with Freezed metadata

---

frb_codegen/src/generator/dart/mod.rs
frb_example/pure_dart/dart/lib/bridge_definitions.dart
frb_example/pure_dart/dart/lib/bridge_definitions.freezed.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.io.dart
frb_example/pure_dart/dart/lib/bridge_generated.web.dart
frb_example/pure_dart/dart/lib/main.dart
frb_example/pure_dart/rust/c_output_path/c_output.h
frb_example/pure_dart/rust/c_output_path_extra/c_output.h
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.io.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/bridge_generated.web.rs

Allow all structs/enums that meet the conditions to be able to generate code correctly through `freezed` because the approach in #1304 may fail under certain circumstances.
- x] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the …

fix: better check for whether the file need to generate freezed structs/enums

---

frb_dart/pubspec.yaml

Fixes a typo in frb_dart/pubspec.yaml. Before: red squiggles in vscode due to pubspec.json validation. After: no squiggles.

fix invalid sdk spec syntax

---

book/src/troubleshooting.md

Fixes #1323.
Note: Codegen is skipped because clippy complains on rust 1.72 now.

document some common android fixes

---

book/src/library/ci.md

Hey👋🏻
In the "Creating a Dart\Flutter Library" chapter of the book and regarding CI/CD:
- I've provided the location of  `pub-credentials.json` file on Windows and it'd be helpful if anyone can double-check.
- Add a lil bit of info on how to locally login to `Pub.dev`.
**And of course thanks to everyone for ur hard work.**

Provide more info for "Creating a Library" chapter, "CI/CD" section

---

frb_codegen/src/commands.rs
frb_example/pure_dart/dart/pubspec.lock
frb_example/pure_dart/dart/pubspec.yaml
frb_example/pure_dart_multi/dart/pubspec.lock
frb_example/pure_dart_multi/dart/pubspec.yaml

Fixes #1329. Tested with `cargo test`. 
Note: In with_flutter, pubspec.yaml cannot be upgraded to ffigen 9 because of a conflicting major version of `file` via flutter sdk `integration_test`. `cargo test` run with 
```yaml
+  ffigen: ^9.0.1
+dependency_overrides:
+  file: ^7.0.0
```

Ffigen version

---

Cargo.lock
frb_codegen/Cargo.toml
frb_codegen/src/generator/dart/ty_sync_return.rs
frb_codegen/src/generator/rust/ty_sync_return.rs
frb_codegen/src/ir/ty_sync_return.rs

This PR replaces the use of `delegate` crate with `delegate-attr` crate to simplify the code while keeping the same functionality.

Use delegate-attr to simplify code

---

book/src/feature/logging.md

The "Logging" page of the book had some small typos, this pr fixes them

Fix small typos in logging.md

---

frb_codegen/src/commands.rs

Fixes #1354 
This PR removes this line of code:
https://github.com/fzyzcjy/flutter_rust_bridge/blob/d54eae758f94ca1a5e69787d20f16af39daa89c2/frb_codegen/src/commands.rs#L321
This code was removing the last line of the output from `cargo-expand`. This caused a `lex error` to be thrown because it removed an important piece of code (ex. `}`).
- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On …

Fix expand missing code

---

frb_codegen/src/parser/error.rs
frb_codegen/src/parser/mod.rs
frb_dart/lib/src/basic.dart
frb_example/pure_dart/dart/lib/bridge_definitions.dart
frb_example/pure_dart/dart/lib/bridge_generated.dart
frb_example/pure_dart/dart/lib/bridge_generated.io.dart
frb_example/pure_dart/dart/lib/bridge_generated.web.dart
frb_example/pure_dart/dart/lib/main.dart
frb_example/pure_dart/rust/c_output_path/c_output.h
frb_example/pure_dart/rust/c_output_path_extra/c_output.h
frb_example/pure_dart/rust/src/api.rs
frb_example/pure_dart/rust/src/bridge_generated.io.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/bridge_generated.web.rs

fix: Err returned in Rust not properly passed to Dart

---

frb_codegen/src/entrypoint/rust.rs
frb_example/pure_dart/rust/src/bridge_generated.rs
frb_example/pure_dart/rust/src/lib.rs
frb_example/pure_dart_multi/rust/src/generated_api_1.rs
frb_example/pure_dart_multi/rust/src/generated_api_2.rs
frb_example/with_flutter/rust/src/bridge_generated.rs

Can't add `#[rustfmt::skip]` for `bridge_generated`
```
error[E0659]: `io` is ambiguous
--> frb_example/pure_dart/rust/src/bridge_generated.rs:4149:9
|
4149 | pub use io::*;
|         ^^ ambiguous name
```

Fix `rustfmt::skip`

---

frb_codegen/src/library/codegen/generator/api_dart/spec_generator/info.rs
frb_codegen/src/library/codegen/ir/ty/rust_opaque.rs
frb_codegen/src/library/codegen/parser/type_parser/rust_auto_opaque.rs
frb_codegen/src/library/codegen/parser/type_parser/rust_opaque.rs
frb_codegen/test_fixtures/library/codegen/parser/mod/generics/expect_ir.json
frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_auto_opaque_twin_sse.dart
frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_auto_opaque_twin_sync.dart
frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_auto_opaque_twin_sync_sse.dart
frb_example/pure_dart/lib/src/rust/api/rust_auto_opaque.dart
frb_example/pure_dart/lib/src/rust/frb_generated.dart
frb_example/pure_dart/lib/src/rust/frb_generated.io.dart
frb_example/pure_dart/lib/src/rust/frb_generated.web.dart
frb_example/pure_dart/test/api/pseudo_manual/rust_auto_opaque_twin_sse_test.dart
frb_example/pure_dart/test/api/pseudo_manual/rust_auto_opaque_twin_sync_sse_test.dart
frb_example/pure_dart/test/api/pseudo_manual/rust_auto_opaque_twin_sync_test.dart
frb_example/pure_dart/test/api/rust_auto_opaque_test.dart

Avoid `RwLock` in generated rust-auto-opaque name

---

frb_rust/src/misc/into_into_dart.rs

For WASM allo-isolate is not used.
This let's for example `./frb_internal precommit --mode fast` fail.

fix: Don't impl test for WASM targets.

---

Cargo.lock
frb_codegen/Cargo.toml

More of a chore which doesn't seem to match this template well. I'm just trying to track down remaining sources of old `clap` version downloads. `cbindgen` is one of those crates that doubles as a library and binary with a default `clap` feature that is only used by the binary. This is the only default feature, so there's no need to have it when using `cbindgen` as a library

Toggle off default `clap` feature for `cbindgen`

---

.github/workflows/ci.yaml
frb_codegen/Cargo.toml
frb_rust/Cargo.toml

- fixes #1454 by adding the MSRV to fab_codegen
=> all passes, except "Benchmark" jobs. They did not pass before this changes either.
- The ci test installs "crate msrv", which verifies that the version set is correct. It can be used to find the correct version number as well - but that should be done locally, not in ci - as the MSRV usually doesn't change ofter. The ci fails only when the MSRV is not working anymore, by installing that version and running cargo check.
- This PR adds a MSRV to frb_codegen only, no other rust crates.
- There are two ways to specify the MSRV in the cargo.toml:
- [platform.rust-version] (which I choose) and 
- [platform.metadata.MSRV]

Fixes #1454 by setting the msrv

---

frb_codegen/assets/integration_template/rust/src/frb_generated.io.rs
frb_codegen/src/library/codegen/generator/wire/dart/spec_generator/codec/cst/encoder/ty/enumeration.rs
frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/codec/cst/decoder/ty/enumeration.rs
frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/extern_func.rs
frb_example/flutter_via_create/rust/src/frb_generated.io.rs
frb_example/flutter_via_integrate/rust/src/frb_generated.io.rs
frb_example/gallery/lib/src/ignore_me/polars_related.dart
frb_example/gallery/lib/src/rust/api/polars.dart
frb_example/gallery/lib/src/rust/frb_generated.dart
frb_example/gallery/lib/src/rust/frb_generated.io.dart
frb_example/gallery/lib/src/rust/frb_generated.web.dart
frb_example/gallery/rust/src/frb_generated.io.rs
frb_example/pure_dart/frb_generated.h
frb_example/pure_dart/lib/src/rust/frb_generated.io.dart
frb_example/pure_dart/rust/src/api/dart_opaque_sync.rs
frb_example/pure_dart/rust/src/api/pseudo_manual/dart_opaque_sync_twin_sse.rs
frb_example/pure_dart/rust/src/frb_generated.io.rs

(CST) Remove `*mut Enum_Variant` and inflate functions in favor of `MaybeUninit`. This reduces 1-2 allocations per enum instantiation and should reduce binary size somewhat.

refactor: remove double-allocation for enum CST decode

---

frb_codegen/src/library/codegen/parser/attribute_parser.rs

Allow `#[frb(one, two)]` (originally only allow `#[frb(one)] #[frb(two)]`)

---

website/docs/manual/integrate/07-library/03-platform-setup/03-android.md
website/v1_mdbook/src/library/platform_setup/android.md

Fix warning of CMake `No project() command is present` for Android build when using the library template in doc

---

website/docs/guides/miscellaneous/properties.md
website/sidebars.js

Thanks @JustSimplyKyle for pointing out the missing doc in https://github.com/fzyzcjy/flutter_rust_bridge/pull/1600#issuecomment-1879899229

Add doc about property getter

---

frb_example/pure_dart/rust/Cargo.lock
frb_example/pure_dart/rust/Cargo.toml
frb_example/pure_dart/rust/example_external_lib/Cargo.toml
frb_example/pure_dart/rust/src/api/mirror.rs
frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_rust_async.rs
frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_rust_async_sse.rs
frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_sse.rs
frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_sync.rs
frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_sync_sse.rs

Fixes a typo in package name, just a find-replace
No issue, fixes a typo

Fix typo in `frb_example_pure_dart_exapmle_external_lib`

---

frb_codegen/assets/integration_template/lib/src/rust/frb_generated.dart

Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/1668

Fix `integrate` command's default template has `rust_lib` hardcoded instead of custom names

---

website/docs/manual/troubleshooting.md

Add doc to explain how to configure ios build system to avoid "linker undefined symbols"

---

frb_codegen/src/library/codegen/polisher/mod.rs

Add checks when build_runner needs to be a dependency

---

frb_codegen/src/library/codegen/polisher/mod.rs
frb_codegen/src/library/commands/command_runner.rs
frb_codegen/src/library/commands/format_dart.rs
frb_codegen/src/library/commands/format_rust.rs
frb_codegen/src/library/integration/integrator.rs
frb_codegen/src/library/internal/frb_rust_source_code.rs

Fix failure of formatting Dart code when path is too long

---

frb_codegen/src/library/codegen/parser/type_parser/structure.rs

for unit struct:
```rust
pub struct App;
```
Error message before: 
```
struct with unit fields are not supported yet, what about using `struct YourStructName {}`
```
Error message after: 
```
struct with unit fields are not supported yet, what about using `struct App {}`
```
which is much more friendly for users to figure how to fix.
PS. I don't know how to write a good test for this ...

More friendly error message for Unit Struct

---

frb_example/dart_build_rs/rust/Cargo.toml
website/docs/guides/miscellaneous/build-rs.md

Fixes #1742 
@fzyzcjy please not that I took the liberty to change the md-file to have one sentence per line. In this way, future changes are easier to see in the diff. The output should not be affected by this reformatting.
Probably my description is a bit to verbose - feel free to reformulate or ask me to do so!

Improves the documentation on how to configure build.rs

---

frb_codegen/src/library/codegen/generator/wire/c/spec_generator/cbindgen_executor.rs
frb_codegen/src/library/codegen/generator/wire/c/spec_generator/dummy_function.rs
frb_example/pure_dart/frb_generated.h
frb_example/pure_dart/lib/src/rust/frb_generated.io.dart

fix(codegen): generate decl of `store_dart_post_cobject` when full_dep enabled

---

frb_example/dart_build_rs/rust/build.rs

This is a simple change, that reruns the `build.rs` for generating the bindings only when the `api` directory changes using the [`"cargo:rerun-if-changed=dir"`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed) instruction.

Only run `build.rs` if `api` directory changes

---

frb_codegen/src/library/codegen/config/config_parser.rs

Problem Description:
Currently there is no way to access `flutter_rust_bridge` options in the `pubspec.yaml` in `build.rs` (without manually parsing it) because it in the rust directory, there is a function `Config::from_config_file` that is used for loading just a config with a specified path (this requires having a separate file `flutter_rust_bridge.yaml` file).
PR:
Expose the already implemented `Config::from_pubspec_yaml` and let it accept a path like `Config::from_config_file`.

Allow specifying `pubspec.yaml` location in `build.rs`

---

frb_codegen/src/library/codegen/ir/mir/ty/enumeration.rs
frb_codegen/src/library/codegen/ir/mir/ty/mod.rs
frb_codegen/src/library/codegen/ir/mir/ty/rust_auto_opaque_implicit.rs
frb_codegen/src/library/codegen/ir/mir/ty/structure.rs
frb_codegen/src/library/codegen/parser/mir/function_parser/argument.rs
frb_codegen/src/library/codegen/parser/mir/function_parser/mod.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/enum_or_struct.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/enumeration.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/misc.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/mod.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/path.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/rust_auto_opaque_implicit.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/structure.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/ty.rs
frb_codegen/src/library/utils/namespace.rs
frb_codegen/test_fixtures/library/codegen/parser/mod/generics/expect_mir.json
frb_codegen/test_fixtures/library/codegen/parser/mod/methods/expect_mir.json
frb_codegen/test_fixtures/library/codegen/parser/mod/use_type_in_another_file/expect_mir.json

Automatically mark methods of non-pub structs as ignored

---

frb_codegen/src/library/codegen/ir/hir/hierarchical/syn_item_struct_or_enum.rs
frb_codegen/src/library/codegen/ir/mir/skip.rs
frb_codegen/src/library/codegen/parser/mir/auto_accessor_parser/mod.rs
frb_codegen/src/library/codegen/parser/mir/function_parser/mod.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/enum_or_struct.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/enumeration.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/misc.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/structure.rs
frb_codegen/test_fixtures/library/codegen/parser/mod/generics/expect_mir.json

Detect and skip functions with generics

---

frb_codegen/src/library/codegen/parser/mir/type_parser/enumeration.rs
frb_codegen/src/library/codegen/parser/mir/type_parser/structure.rs

Auto detect as opaque when third party struct/enum has non public field

---

frb_codegen/src/library/codegen/parser/mir/function_parser/output.rs

Auto convert reference type in return type as unit type

---

frb_codegen/src/library/codegen/ir/hir/hierarchical/function.rs
frb_codegen/src/library/codegen/ir/hir/hierarchical/misc.rs
frb_codegen/src/library/codegen/ir/hir/hierarchical/mod.rs
frb_codegen/src/library/codegen/ir/hir/hierarchical/struct_or_enum.rs
frb_codegen/src/library/codegen/ir/hir/hierarchical/traits.rs
frb_codegen/src/library/codegen/parser/hir/flat/mod.rs
frb_codegen/src/library/codegen/parser/hir/hierarchical/module/pub_use_transformer.rs
frb_codegen/src/library/codegen/parser/hir/hierarchical/pack/trait_impl_transformer.rs
frb_codegen/src/library/utils/namespace.rs
frb_codegen/test_fixtures/library/codegen/parser/mod/generics/expect_hir_hierarchical.json
frb_codegen/test_fixtures/library/codegen/parser/mod/methods/expect_hir_hierarchical.json
frb_codegen/test_fixtures/library/codegen/parser/mod/multi_input_file/expect_hir_hierarchical.json
frb_codegen/test_fixtures/library/codegen/parser/mod/non_qualified_names/expect_hir_hierarchical.json
frb_codegen/test_fixtures/library/codegen/parser/mod/qualified_names/expect_hir_hierarchical.json
frb_codegen/test_fixtures/library/codegen/parser/mod/simple/expect_hir_hierarchical.json
frb_codegen/test_fixtures/library/codegen/parser/mod/use_type_in_another_file/expect_hir_hierarchical.json

Improve pub use parsing and trait definition parsing in third party crates

---

frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/method.rs
frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/proxy_variant.rs
frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/ty/delegate.rs
frb_codegen/src/library/codegen/generator/api_dart/spec_generator/info.rs
frb_codegen/src/library/codegen/generator/codec/sse/ty/delegate.rs
frb_codegen/src/library/codegen/ir/early_generator/mod.rs
frb_codegen/src/library/codegen/ir/early_generator/pack.rs
frb_codegen/src/library/codegen/ir/early_generator/proxied_type.rs
frb_codegen/src/library/codegen/ir/mir/ty/delegate.rs
frb_codegen/src/library/codegen/parser/early_generator/proxy_enum.rs
frb_codegen/src/library/codegen/parser/mir/parser/function/real/argument.rs
frb_codegen/src/library/codegen/parser/mir/parser/mod.rs
frb_codegen/src/library/codegen/parser/mir/parser/ty/mod.rs
frb_codegen/src/library/codegen/parser/mir/parser/ty/ty.rs
frb_dart/lib/flutter_rust_bridge_for_generated_common.dart
frb_dart/lib/src/misc/simple_disposable.dart
frb_example/dart_minimal/lib/src/rust/api/minimal.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.freezed.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.io.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.web.dart
frb_example/dart_minimal/rust/src/api/minimal.rs
frb_example/dart_minimal/rust/src/frb_generated.rs

Support `#[frb(proxy)]` (part 1)

---

frb_codegen/src/library/codegen/parser/hir/tree/parser/crates.rs
frb_codegen/src/library/codegen/parser/hir/tree/parser/module.rs
frb_codegen/src/library/codegen/parser/mir/parser/attribute.rs
frb_example/pure_dart/rust/src/api/deliberately_ignored_module.rs
frb_example/pure_dart/rust/src/api/mod.rs
frb_example/pure_dart_pde/rust/src/api/deliberately_ignored_module.rs
frb_example/pure_dart_pde/rust/src/api/mod.rs
tools/frb_internal/lib/src/frb_example_pure_dart_generator/misc_generator.dart

Support ignoring a whole module by `#[frb(ignore)]` on module ; Support `/// frb:...`

---

frb_codegen/src/library/codegen/generator/codec/sse/ty/structure.rs
frb_codegen/src/library/codegen/parser/mir/parser/function/auto_accessor/field.rs
frb_example/integrate_third_party/lib/src/rust/frb_generated.dart
frb_example/integrate_third_party/rust/src/frb_generated.rs
frb_example/pure_dart/frb_generated.h
frb_example/pure_dart/lib/src/rust/api/constructor.dart
frb_example/pure_dart/lib/src/rust/api/dyn_trait.dart
frb_example/pure_dart/lib/src/rust/api/misc_no_twin_example_a.dart
frb_example/pure_dart/lib/src/rust/frb_generated.web.dart
frb_example/pure_dart/rust/src/frb_generated.io.rs
frb_example/pure_dart/rust/src/frb_generated.web.rs
frb_example/pure_dart_pde/lib/src/rust/api/constructor.dart
frb_example/pure_dart_pde/lib/src/rust/api/dyn_trait.dart
frb_example/pure_dart_pde/lib/src/rust/api/misc_no_twin_example_a.dart
frb_example/pure_dart_pde/lib/src/rust/frb_generated.dart
frb_example/pure_dart_pde/rust/src/frb_generated.rs

Add fixed prefix `auto_accessor` for auto-generated reflection methods signatures, which is used as reflections for fields within Rust types tagged with `#[frb(opaque)]`.
Related issue: https://github.com/fzyzcjy/flutter_rust_bridge/issues/2079

Add prefix for automatically generated get/set methods of `#[frb(opaque)]` types to avoid conflicting with existing methods

---

frb_dart/lib/src/cli/build_web/executor.dart

Improve hints when user specify custom wasm-pack-rustflags but does not contain default one

---

frb_codegen/src/library/integration/creator.rs

The folders android, ios, linux, windows and macos aren't always available after flutter create for plugins. Check if they exist before cleaning them up. This is to avoid runtime errors when trying to change into non-existing folders.
Fixes #2208

Don't try to cleanup folders that don't exist

---

Cargo.toml
frb_rust/Cargo.toml
frb_rust/src/misc/user_utils.rs

Support logging on macOS in the same way as iOS.
Logs can be viewed through Instruments and Console.

feat: support macos log

---

frb_codegen/assets/integration_template/shared/REPLACE_ME_RUST_CRATE_DIR/Cargo.lock.template
frb_example/dart_build_rs/rust/Cargo.lock
frb_example/dart_minimal/rust/Cargo.lock
frb_example/deliberate_bad/rust/Cargo.lock
frb_example/flutter_package/rust/Cargo.lock
frb_example/flutter_via_create/rust/Cargo.lock
frb_example/flutter_via_integrate/rust/Cargo.lock
frb_example/gallery/rust/Cargo.lock
frb_example/integrate_third_party/rust/Cargo.lock
frb_example/pure_dart/rust/Cargo.lock
frb_example/pure_dart_pde/rust/Cargo.lock
frb_example/rust_ui_counter/Cargo.lock
frb_example/rust_ui_todo_list/Cargo.lock
frb_rust/Cargo.toml

Make `log` crate feature enabled by default

---

frb_codegen/assets/integration_template/shared/lib/src/rust/frb_generated.dart
frb_codegen/src/library/codegen/generator/wire/dart/spec_generator/misc/mod.rs
frb_dart/lib/src/main_components/entrypoint.dart
frb_example/dart_build_rs/lib/src/rust/frb_generated.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.dart
frb_example/deliberate_bad/lib/src/rust/frb_generated.dart
frb_example/flutter_package/lib/src/rust/frb_generated.dart
frb_example/flutter_via_create/lib/src/rust/frb_generated.dart
frb_example/flutter_via_integrate/lib/src/rust/frb_generated.dart
frb_example/gallery/lib/src/rust/frb_generated.dart
frb_example/integrate_third_party/lib/src/rust/frb_generated.dart
frb_example/pure_dart_pde/lib/src/rust/frb_generated.dart
frb_example/rust_ui_counter/ui/lib/src/rust/frb_generated.dart
frb_example/rust_ui_todo_list/ui/lib/src/rust/frb_generated.dart

feat: mock mode

---

frb_codegen/src/library/codegen/polisher/mod.rs
frb_codegen/src/library/commands/dart_fix.rs
frb_codegen/src/library/integration/integrator.rs

/cc @AlexV525 
Otherwise it error like:
```
6.8s] Parse ⠂
[2024-09-11T12:20:37.601Z WARN frb_codegen/src/library/commands/command_runner.rs:153] command=cd "/Volumes/MyExternal/ExternalRefCode/flutter_rust_bridge/frb_example/dart_minimal" && "sh" "-c" "\"dart\" \"fix\" \"--apply\" \"lib/src/rust/api/minimal.dart\" \"lib/src/rust/frb_generated.io.dart\" \"lib/src/rust/frb_generated.web.dart\" \"lib/src/rust/frb_generated.dart\"" stdout= stderr=Only one file or directory is expected.
Usage: dart fix [arguments]
-h, --help                      Print this usage information.
-n, --dry-run                   Preview the proposed changes but make no changes.
--apply                     Apply the proposed changes.
--code=<code1,code2,...>    Apply fixes for one (or more) diagnostic codes.
Run …
```

Fix `dart fix` command line arg

---

website/docs/guides/misc-features/dart-code.md

@fzyzcjy  I rewrote the #[frb(dart_code = )] documentation to more clearly state how to use it, troubleshoot it, and its (current) limitations.
I verified all statements with little experiments. However, please correct me if I stated something wrongly.

improves the dart_code documentation

---

Cargo.lock
frb_codegen/Cargo.toml
frb_example/dart_build_rs/rust/Cargo.lock

Upgrade `serde_yaml` to the newest released version (0.9). `serde_yaml` `0.8` depends on the unmaintained `yaml-rust` [RUSTSEC-2024-0320](https://rustsec.org/advisories/RUSTSEC-2024-0320.html), and an upgrade didn't seem to break anything. Point of discussion is that `serde_yaml` is now archived/deprecated entirely and will probably be marked as unmaintained in the near future as well https://github.com/rustsec/advisory-db/issues/1925.
- [-] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
- [-] If this PR adds/changes features, documentations (in the `./website` folder) are updated.
- If fzyzcjy does not …

Upgrade serde yaml

---

frb_codegen/src/binary/commands.rs
frb_codegen/src/main.rs
website/docs/generated/_frb-codegen-command-create.mdx
website/docs/generated/_frb-codegen-command-integrate.mdx

Addresses #2334 by adding a warning if a user provides a absolute Path, and extend the documentation on the Clap doc string. 
Close #2334 (<--- edited by fzyzcjy to allow github auto close that)

Add docs and warning if user provides absolute rust_crate_dir

---

frb_codegen/src/library/commands/dart_build_runner.rs
frb_codegen/src/library/commands/dart_fix.rs
frb_codegen/src/library/commands/dart_format.rs
frb_codegen/src/library/commands/flutter.rs
frb_codegen/src/library/commands/fvm.rs
frb_codegen/src/library/commands/mod.rs

Auto detect and use `fvm`

---

frb_codegen/src/library/utils/dart_repository/dart_toolchain.rs

Fix call dart/flutter toolchain --version with fvm support.

Fix call toolchain version with fvm support

---

frb_codegen/src/library/codegen/generator/codec/sse/ty/enumeration.rs

Removes the `default` case that is no longer needed in Dart 3.0
Context: rhttp is getting analyzer warnings: https://pub.dev/packages/rhttp/versions/0.9.6/score
Running any `./frb_internal` command gets stuck at `Running /Users/<User>/flutter_rust_bridge/target/debug/flutter_rust_bridge_codegen generate` at some point. So I could not update the resources

feat: remove default case in enums

---

Cargo.lock
frb_codegen/Cargo.toml
frb_example/dart_build_rs/rust/Cargo.lock

Fixes #2491 
```
[2025-02-15T00:28:04.985Z WARN index.crates.io-1949cf8c6b5b557f/flutter_rust_bridge_codegen-2.8.0/src/library/codegen/polisher/mod.rs:108] Fail to auto_upgrade, but continue to run.
Error details: Err(can't load root workspace
Caused by:
0: TOML parse error at line 11, column 11
|
11 | edition = "2024"
|           ^^^^^^
unknown variant `2024`, expected one of `2015`, `2018`, `2021`
1: TOML parse error at line 11, column 11
|
11 | edition = "2024"
|           ^^^^^^
unknown variant `2024`, expected one of `2015`, `2018`, `2021`
)
```

[fix] add support for rust edition 2024

---

frb_codegen/src/library/codegen/generator/wire/dart/spec_generator/codec/dco/decoder/ty/primitive.rs

I started using the `strict-casts` lint (https://dart.dev/tools/analysis#enabling-additional-type-checks) and then my `frb_generated.dart` contained errors.
It's not a big issue as this file can be excluded from the analyzer and this lint is optional anyway, but I thought it would be nice that everything would work out-of-the box for people enabling this lint.
Feel free to disagree, it's not important.

Fix for strict-casts lint

---

Cargo.lock
frb_dart/lib/src/wasm_module/_web.dart
frb_example/dart_build_rs/rust/Cargo.lock
frb_example/dart_minimal/rust/Cargo.lock
frb_example/deliberate_bad/rust/Cargo.lock
frb_example/flutter_package/rust/Cargo.lock
frb_example/flutter_via_create/rust/Cargo.lock
frb_example/flutter_via_integrate/rust/Cargo.lock
frb_example/gallery/rust/Cargo.lock
frb_example/integrate_third_party/rust/Cargo.lock
frb_example/pure_dart/rust/Cargo.lock
frb_example/pure_dart_pde/rust/Cargo.lock
frb_example/rust_ui_counter/Cargo.lock
frb_example/rust_ui_todo_list/Cargo.lock
frb_rust/src/third_party/wasm_bindgen/worker_pool.rs

Close #2578
* Run tests: `./frb_internal test-dart-native --package frb_example/dart_minimal`

Upgrade calls to wasm-bindgen

---

frb_codegen/src/library/codegen/ir/mir/field.rs
frb_codegen/src/library/codegen/parser/mir/parser/attribute.rs
frb_codegen/src/library/codegen/parser/mir/parser/function/auto_accessor/mod.rs
frb_codegen/src/library/codegen/parser/mir/parser/ty/enumeration.rs
frb_codegen/src/library/codegen/parser/mir/parser/ty/structure.rs
frb_codegen/test_fixtures/library/codegen/parser/mod/generics/expect_mir.json
frb_codegen/test_fixtures/library/codegen/parser/mod/methods/expect_mir.json
frb_codegen/test_fixtures/library/codegen/parser/mod/non_qualified_names/expect_mir.json
frb_codegen/test_fixtures/library/codegen/parser/mod/qualified_names/expect_mir.json
frb_codegen/test_fixtures/library/codegen/parser/mod/unused_struct_enum/expect_mir.json
frb_codegen/test_fixtures/library/codegen/parser/mod/use_type_in_another_file/expect_mir.json
frb_example/dart_minimal/lib/src/rust/api/minimal.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.io.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.web.dart
frb_example/dart_minimal/rust/src/api/minimal.rs
frb_example/dart_minimal/rust/src/frb_generated.rs
frb_example/dart_minimal/test/ignore.dart

Fixes #2720.
This additionally adds a `#[frb(ignore_all)]` attribute to skip all fields, but I could drop it if you'd prefer not to add that.

Implement `#[frb(ignore)]` for struct fields

---

Cargo.lock
frb_example/dart_build_rs/rust/Cargo.lock
frb_example/dart_minimal/rust/Cargo.lock
frb_example/deliberate_bad/rust/Cargo.lock
frb_example/flutter_package/rust/Cargo.lock
frb_example/flutter_via_create/rust/Cargo.lock
frb_example/flutter_via_integrate/rust/Cargo.lock
frb_example/gallery/rust/Cargo.lock
frb_example/integrate_third_party/rust/Cargo.lock
frb_example/pure_dart/rust/Cargo.lock
frb_example/pure_dart_pde/rust/Cargo.lock
frb_example/rust_ui_counter/Cargo.lock
frb_example/rust_ui_todo_list/Cargo.lock
frb_rust/Cargo.toml

Just bumping logging for android & ios which prevent automatic dependency resolution for regex crate to 1.11. Awfully specific, but also just a bump pr :) 

bump logging dependecies to help dependency resolution for regex crate

---

.github/workflows/ci.yaml
.github/workflows/post_release.yaml
frb_codegen/assets/integration_template/shared/lib/src/rust/frb_generated.dart
frb_codegen/src/library/codegen/generator/wire/dart/spec_generator/misc/mod.rs
frb_dart/lib/src/main_components/entrypoint.dart
frb_dart/test/entrypoint_test.dart
frb_example/dart_build_rs/lib/src/rust/frb_generated.dart
frb_example/dart_minimal/lib/src/rust/frb_generated.dart
frb_example/deliberate_bad/lib/src/rust/frb_generated.dart
frb_example/flutter_package/lib/src/rust/frb_generated.dart
frb_example/flutter_via_create/lib/src/rust/frb_generated.dart
frb_example/flutter_via_integrate/lib/src/rust/frb_generated.dart
frb_example/gallery/lib/src/rust/frb_generated.dart
frb_example/integrate_third_party/lib/src/rust/frb_generated.dart
frb_example/pure_dart_pde/lib/src/rust/frb_generated.dart
frb_example/rust_ui_counter/ui/lib/src/rust/frb_generated.dart
frb_example/rust_ui_todo_list/ui/lib/src/rust/frb_generated.dart

Per offline discussion, some generated libraries will not change after upgrades, so checking their version would cause extra effort for maintainers to upgrade periodically.
Introducing `forceSameCodegenVersion` to allow users to bypass the check when they feel confident to do so.

🧑‍💻 Allow bypassing codegen version check and produce log when enabled assertion

---

frb_codegen/src/library/commands/fvm.rs

fix: use `fvm install` to prevent `flutter_rust_bridge_codegen generate` from hanging (closes #2832)
