.github/workflows/ci.yaml, frb_codegen/src/api_types.rs, frb_codegen/src/generator_dart.rs, frb_codegen/src/generator_rust.rs, frb_codegen/src/parser.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/dart/pubspec.lock, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/with_flutter/lib/bridge_generated.dart, frb_example/with_flutter/pubspec.lock, justfile
Solves #191.
~~Blocker: Dart generator is creating unused code, I'm trying to find a workaround before declaring this mergeable.~~ Done!
=> Implement `Vec<String>`

frb_codegen/src/api_types.rs, frb_codegen/src/generator_dart.rs, frb_codegen/src/parser.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs
This is my first try of adding support for the unit return type.
I don't have much experience with Dart so please treat with care.
Fixes #197.
=> Add support for unit return type.

frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs
The test currently fails and demonstrates bug #234.
=> Add test for passing and returning u32.

CHANGELOG.md, frb_codegen/src/api_types.rs, frb_codegen/src/generator_dart.rs, frb_codegen/src/generator_rust.rs, frb_codegen/src/parser.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/dart/pubspec.lock, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/with_flutter/pubspec.lock, justfile
=> Simple field-less enums

frb_codegen/src/api_types.rs, frb_codegen/src/generator_dart.rs, frb_codegen/src/generator_rust.rs, frb_codegen/src/parser.rs, frb_codegen/src/transformer.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/dart/pubspec.lock, frb_example/pure_dart/dart/pubspec.yaml, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/with_flutter/rust/src/bridge_generated.rs, justfile
Partly resolves #249. Some additional testing may be needed.
=> Enum structs

frb_example/pure_dart/rust/Cargo.toml.release, frb_rust/Cargo.toml.release
=> Add Cargo.toml.release for Rust runtime library

frb_codegen/src/api_types.rs, frb_codegen/src/generator_dart.rs, frb_codegen/src/generator_rust.rs, frb_codegen/src/parser.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_macros/src/lib.rs
Several small fixes and improvements:
- Resolve #265
- Resolve #266
- Fix attributes not working on enum variants
- Add comments on enum variants and fields
- (Internal) unify tuple and normal enum structs
=> Enum struct improvements

frb_codegen/src/generator_rust.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/with_flutter/ios/Runner/bridge_generated.h, frb_example/with_flutter/lib/bridge_generated.dart, frb_example/with_flutter/rust/src/bridge_generated.rs, justfile
=> Avoid user parameter collision in wire functions

frb_codegen/src/commands.rs
=> Quote arguments when calling external commands

frb_codegen/src/source_graph.rs
=> Don't panic on import renames

.github/workflows/ci.yaml, frb_example/with_flutter/linux/rust.require.cmake
To determine issues running with and without Corrosion preinstalled on Windows and Linux.
=> Run CI requiring Corrosion

book/src/integrate.md, book/src/integrate/desktop.md, book/src/template/setup_desktop.md, book/src/template/setup_ios.md, book/src/template/tour_justfile.md
Fix broken links and adjusted wording.
=> Minor document tweaks

frb_codegen/src/generator/rust/mod.rs, frb_codegen/src/generator/rust/ty.rs, frb_codegen/src/generator/rust/ty_boxed.rs, frb_codegen/src/generator/rust/ty_enum.rs, frb_codegen/src/generator/rust/ty_general_list.rs, frb_codegen/src/generator/rust/ty_optional.rs, frb_codegen/src/generator/rust/ty_struct.rs, frb_codegen/src/ir/field.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/external/src/lib.rs, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs
Add support for tuple structs, enum variants, wrapping in Vec and Optional.
There are still cases where it's not working, especially with Box (and sending back Vec).
It would also be nice to have it working for StreamSink but I'm not sure how to go about it.
=> Make mirroring work for more use cases

.github/workflows/ci.yaml, frb_codegen/src/others.rs, frb_example/pure_dart/rust/src/api.rs, justfile
=> Windows CI improvements

book/src/tutorial_with_flutter.md
Hi, thanks for the project.
I stumble upon these 2 issues while following the tutorial.
I hope this could help future readers.
=> Doc Improvement on Tutorial with Flutter

frb_codegen/src/generator/dart/ty_boxed.rs, frb_codegen/src/generator/dart/ty_enum.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs
=> Fix extra comma in enum structs

frb_codegen/src/generator/rust/ty_enum.rs, frb_example/pure_dart/rust/src/bridge_generated.rs
=> Add IntoDartExceptPrimitive impl for enums

frb_example/pure_dart/rust/Cargo.lock, frb_example/with_flutter/rust/Cargo.lock
NOTE: https://github.com/sagudev/flutter_rust_bridge/runs/6277947055?check_suite_focus=true failed two times on my CI
=> update all deps in locks

frb_example/pure_dart/rust/Cargo.lock, frb_example/with_flutter/rust/Cargo.lock
Reverts fzyzcjy/flutter_rust_bridge#441
=> Revert "update all deps in locks"

frb_rust/src/handler.rs
=> fix typo in handler.rs

book/src/tutorial_with_flutter.md
As said in https://github.com/fzyzcjy/flutter_rust_bridge/discussions/483#discussioncomment-2885738
=> book(tutorial): update the android building process

.github/workflows/ci.yaml, frb_codegen/src/generator/dart/mod.rs
- split the big function up into some smaller functions with descriptive names
Feedback is welcome 🙂
=> cleaned up `generate()` in `dart/mod.rs`

book/src/integrate/android_tasks.md
Fixes #579
these changes are only related to the documentation, so it seems like there is no need for automated testing?
=> change to doc #579

frb_codegen/src/commands.rs
This PR follows the issue #406.
I'm gonna need your recommendation @fzyzcjy on how to correctly differentiate a Dart from a Flutter project, hence the draft.
=> Run build_runner either for Dart or Flutter

frb_codegen/src/generator/dart/ty.rs, frb_codegen/src/generator/dart/ty_delegate.rs, frb_codegen/src/generator/dart/ty_struct.rs
=> Code cleanup

frb_codegen/src/markers.rs, frb_codegen/src/source_graph.rs, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.freezed.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/external/src/lib.rs, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.rs
Remark for PR creator: If the PR is submitted but the owner (fzyzcjy) does not reply for a few days, maybe he just did not see it, so please ping him.
=> enhance mirror

frb_codegen/src/commands.rs, frb_codegen/src/config.rs, frb_codegen/src/lib.rs
=> Add cli arg to skip dependencies check

.github/workflows/ci.yaml, .github/workflows/post_release.yaml
Remark for PR creator: If the PR is submitted but the owner (fzyzcjy) does not reply for a few days, maybe he just did not see it, so please ping him.
=> Fix CI error after Flutter releases 3.3

frb_example/pure_dart/dart/pubspec.lock, frb_example/pure_dart/dart/pubspec.yaml
Reverts fzyzcjy/flutter_rust_bridge#660
=> Revert "⬆️ Bump test from 1.21.4 to 1.21.5 in /frb_example/pure_dart/dart"

.github/workflows/gh-pages.yaml, book/src/template/setup_web.md, book/src/tutorial_with_flutter.md, book/src/wasm_limitations.md
Resolves #684 and resolves #682
=> Setup `mdbook-mermaid` on CI

.github/workflows/ci.yaml
=> Use retry actions for flaky CI steps

book/src/tutorial_with_flutter.md
This work is in the public domain, but Wikipedia is credited rather than the creator.
=> Fix image credit in book

.github/workflows/gh-pages.yaml, book/book.toml, book/src/SUMMARY.md, book/src/article/generate_multiple_files.md, book/src/feature/lang_chrono.md, book/src/feature/lang_simple.md, book/src/feature/lang_uuid.md, book/src/integrate/deps.md, book/src/template/generate.md
Reverts fzyzcjy/flutter_rust_bridge#736
=> Revert "Fix broken links in book"

book/src/troubleshooting.md
See https://github.com/fzyzcjy/flutter_rust_bridge/issues/757
=> Add caveat on Kind in type name

.github/workflows/release.yaml
=> Update release workflow to accommodate workspace

README.md, frb_codegen/src/generator/dart/mod.rs, frb_codegen/src/generator/dart/ty_boxed.rs, frb_codegen/src/generator/dart/ty_delegate.rs, frb_codegen/src/generator/dart/ty_primitive_list.rs, frb_codegen/src/generator/rust/ty_boxed.rs, frb_codegen/src/generator/rust/ty_delegate.rs, frb_codegen/src/ir/ty.rs, frb_codegen/src/ir/ty_boxed.rs, frb_codegen/src/ir/ty_delegate.rs, frb_codegen/src/parser/mod.rs, frb_codegen/src/parser/ty.rs, frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.io.dart, frb_example/pure_dart/dart/lib/bridge_generated.web.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/dart/pubspec.lock, frb_example/pure_dart/dart/pubspec.yaml, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.io.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/pure_dart/rust/src/bridge_generated.web.rs, frb_rust/src/ffi/web.rs, frb_rust/src/support.rs
Close #572
Remark for PR creator: If the PR is submitted but the owner (fzyzcjy) does not reply for a few days, maybe he just did not see it, so please ping him.
=> init suport array

frb_codegen/src/generator/dart/func.rs, frb_codegen/src/generator/dart/mod.rs, frb_codegen/src/generator/dart/ty_struct.rs, frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.io.dart, frb_example/pure_dart/dart/lib/bridge_generated.web.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.io.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/pure_dart/rust/src/bridge_generated.web.rs, frb_example/pure_dart_multi/dart/lib/bridge_generated_api_1.dart, frb_example/pure_dart_multi/dart/lib/bridge_generated_api_2.dart, frb_example/with_flutter/lib/bridge_generated.dart
=> Fix return for struct with methods

book/src/feature/lang_dynamic.md
=> Added documentation for dynamic types workaround

Cargo.toml
=> Set default version strategy requirement for chrono

book/src/feature/item_type.md, frb_codegen/src/parser/mod.rs, frb_codegen/src/parser/ty.rs, frb_codegen/src/source_graph.rs, frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.io.dart, frb_example/pure_dart/dart/lib/bridge_generated.web.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.io.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/pure_dart/rust/src/bridge_generated.web.rs, frb_example/pure_dart/rust/src/data.rs
support some code like `pub type Id = u64;`
=> Part of support ItemType

book/src/library/overview.md, book/src/library/setup.md
Adds some minor modifications to the library section of the docs.
=> clean up wording and fix broken link

Cargo.lock, frb_codegen/Cargo.toml, frb_codegen/src/parser/mod.rs, frb_codegen/src/parser/ty.rs, frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.io.dart, frb_example/pure_dart/dart/lib/bridge_generated.web.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.io.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/pure_dart/rust/src/bridge_generated.web.rs, frb_example/pure_dart/rust/src/data.rs
=> support nest type alias with topology sort

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, book/src/feature/misc.md, book/src/help.serve.txt, frb_dart/bin/serve.dart, frb_dart/bin/serve.g.dart, frb_example/pure_dart/rust/Cargo.toml, frb_example/pure_dart/rust/Cargo.toml.release, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/api/helpers.rs, frb_rust/Cargo.toml, frb_rust/src/wasm_bindgen_src/pool.rs, justfile
=> feat: allow opt-out of WASM initializer

book/src/feature/handler.md
This PR clarifies some explanations included in `handler.md` docs file. It also adds an example using `SimpleHandler`.
- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory, You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce erorrs as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
=> Improve handler docs

frb_codegen/src/config.rs, frb_codegen/src/lib.rs
This pr is for refining, no new feature introduced.
For the "refractor" task, actually I have done it when making a draft to solve https://github.com/fzyzcjy/flutter_rust_bridge/issues/987. But I think it would be too heavy to post all changes together in 1 pr. So I post the refractor change here.
=> Refractor and refine for frb_codegen

frb_codegen/src/generator/dart/func.rs, frb_codegen/src/generator/dart/ty_struct.rs, frb_codegen/src/parser/mod.rs, frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/rust/src/api.rs, justfile
Part of #960. (Please don't release immediately, there are more changes left in the series)
=> feat: translate Rust method comments

frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.io.dart, frb_example/pure_dart/dart/lib/bridge_generated.web.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/c_output_path/c_output.h, frb_example/pure_dart/rust/c_output_path_extra/c_output.h, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.io.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/pure_dart/rust/src/bridge_generated.web.rs, frb_example/pure_dart/rust/src/data.rs, frb_rust/src/ffi/mod.rs
Fixes #988
Not sure if documentation is needed for this, since it should be self-explanatory.
=> RustOpaque::Clone has Incorrect Bounds

.github/workflows/ci.yaml, justfile
=> Improve CI and fix #1174

.github/actions/setup/action.yaml, .github/workflows/ci.yaml, .github/workflows/no_response.yml, .github/workflows/post_release.yaml, justfile
=> change ci with cache(part2 of #1174)

.github/workflows/post_release.yaml, frb_example/pure_dart/rust/Cargo.toml.release
Fixed `Post-Release` #1168 
* Removed wrong syntax in `post_release.yaml`
* Fixed desynced release config
Just some small fix :)
=> Fix Workflow Post-Release

CHANGELOG.md, frb_codegen/src/generator/dart/ty_delegate.rs, frb_codegen/src/generator/rust/ty_enum.rs, frb_codegen/src/main.rs, frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.io.dart, frb_example/pure_dart/dart/lib/bridge_generated.web.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/c_output_path/c_output.h, frb_example/pure_dart/rust/c_output_path_extra/c_output.h, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.io.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/pure_dart/rust/src/bridge_generated.web.rs, frb_rust/src/dart_api/dart_api.h, frb_rust/src/dart_api/dart_api_dl.h, frb_rust/src/dart_api/dart_native_api.h, frb_rust/src/dart_api/dart_tools_api.h
added `impl Default` for enum in rust
and `as int` for enum in dart
=> fix enum as struct field; fix errors in strict dynamic error

book/src/feature.md
=> fix: added correct link for ffi docs of android, ios and macos

CONTRIBUTING.md
Corrects broken link to contributors guide
=> update contributing link path

frb_example/pure_dart/dart/lib/bridge_definitions.dart, frb_example/pure_dart/dart/lib/bridge_generated.dart, frb_example/pure_dart/dart/lib/bridge_generated.io.dart, frb_example/pure_dart/dart/lib/bridge_generated.web.dart, frb_example/pure_dart/dart/lib/main.dart, frb_example/pure_dart/rust/c_output_path/c_output.h, frb_example/pure_dart/rust/c_output_path_extra/c_output.h, frb_example/pure_dart/rust/src/api.rs, frb_example/pure_dart/rust/src/bridge_generated.io.rs, frb_example/pure_dart/rust/src/bridge_generated.rs, frb_example/pure_dart/rust/src/bridge_generated.web.rs, frb_rust/src/handler.rs
=> fix and test for SyncReturn of mirrored type

book/src/library/overview.md
=> fix broken relative link

frb_dart/test/README.md, frb_example/pure_dart/dart/bin/pure_dart.dart, frb_example/pure_dart/dart/run.sh, frb_example/pure_dart_multi/dart/bin/pure_dart_multi.dart, frb_example/pure_dart_multi/dart/run.sh
=> Enhance Flutter / Dart test conventions

.github/workflows/ci.yaml, frb_codegen/assets/integration_template/integration_test/simple_test.dart, frb_example/flutter_via_create/integration_test/simple_test.dart, frb_example/flutter_via_integrate/integration_test/simple_test.dart
=> Try to fix flaky CI while no real bug

frb_codegen/src/library/codegen/mod.rs
=> Hint user generation is done

frb_example/pure_dart/benchmark/src/generated.dart, frb_example/pure_dart/frb_generated.h, frb_example/pure_dart/lib/src/rust/api/benchmark_misc.dart, frb_example/pure_dart/lib/src/rust/frb_generated.dart, frb_example/pure_dart/lib/src/rust/frb_generated.io.dart, frb_example/pure_dart/lib/src/rust/frb_generated.web.dart, frb_example/pure_dart/rust/src/api/benchmark_misc.rs, frb_example/pure_dart/rust/src/frb_generated.io.rs, frb_example/pure_dart/rust/src/frb_generated.rs, frb_example/pure_dart/rust/src/frb_generated.web.rs, tools/frb_internal/lib/src/frb_example_pure_dart_generator/dart/benchmark.dart
=> Add frbSse bench test and fix frbCstSse test forget to be sync

tools/frb_internal/lib/src/makefile_dart/generate.dart, tools/frb_internal/lib/src/makefile_dart/misc.dart
=> Allow skip all-contributor for local script

website/src/pages/guides/performance/dashboard.tsx
=> Fix benchmark dashboard

frb_dart/lib/flutter_rust_bridge_for_generated_io.dart, frb_dart/lib/src/dart_c_object_into_dart/_io.dart, frb_example/pure_dart/test/with_vm_service_test.dart, frb_rust/src/misc/into_into_dart.rs, justfile, website/docs/guides/contributing/tip.md, website/docs/guides/types/translatable/zero-copy.md
* https://github.com/fzyzcjy/yplusplus/issues/11611
* https://github.com/fzyzcjy/yplusplus/issues/11613
=> Fix performance bug (for the benchmark case of transferring 1MB data from Rust to Dart)

frb_codegen/src/library/codegen/config/internal_config_parser.rs, frb_codegen/test_fixtures/library/codegen/config/internal_config_parser/faulty_rust_output/flutter_rust_bridge.yaml
Fixes #1539
Documentation not needed.
=> Improve error message when a file ending is not provided in configuration

frb_codegen/src/binary/commands_parser.rs, frb_codegen/src/library/codegen/config/config.rs, frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/codec/cst/decoder/ty/enumeration.rs, frb_codegen/test_fixtures/binary/commands_parser/faulty_pubspec_yaml/pubspec.yaml, frb_codegen/test_fixtures/binary/commands_parser/flutter_rust_bridge_yaml/faulty_flutter_rust_bridge.yaml
Fixes #the-issue-number: #1508 and partially #1458 
(#1458 needs a correction in the documentation, which I leave up to @fzyzcjy)
=> fixes #1508 and partially #1458 by adding configuration to fail when a field is wrong

website/misc/advantages.svg
The correct noun form for powerful is actually just power, which is the root. Similarly, the noun form of simple is simplicity.
There's no PR for this because it's merely a minor edit to the text of an image.
=> Fix grammar in advantages.svg

frb_codegen/src/library/codegen/parser/attribute_parser.rs, frb_codegen/src/library/codegen/parser/function_parser/mod.rs, frb_example/pure_dart/rust/src/api/attribute.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/attribute_twin_rust_async.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/attribute_twin_rust_async_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/attribute_twin_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/attribute_twin_sync.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/attribute_twin_sync_sse.rs, website/docs/guides/miscellaneous/Ignoring Functions.md
Fixes https://github.com/fzyzcjy/flutter_rust_bridge/issues/1542
=> Support ignoring a function via `#[frb(ignore)]`

website/docs/guides/custom/custom_rust_folder.md
Documents customizing the rust project folder as done in #1459.
@fzyzcjy have a look and merge it at your convince.
=> documents customizing the rust folder location

website/docs/guides/miscellaneous/upgrade.md
=> Improve upgrade.md by adding detailed clean up steps

frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/ty/rust_opaque.rs, frb_codegen/src/library/codegen/generator/wire/dart/spec_generator/codec/dco/decoder/ty/rust_opaque.rs, frb_example/gallery/lib/src/rust/api/polars.dart, frb_example/gallery/lib/src/rust/frb_generated.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_auto_opaque_twin_sse.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_auto_opaque_twin_sync.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_auto_opaque_twin_sync_sse.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_opaque_sync_twin_sse.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_opaque_twin_rust_async.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_opaque_twin_rust_async_sse.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_opaque_twin_sse.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_opaque_twin_sync.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/rust_opaque_twin_sync_sse.dart, frb_example/pure_dart/lib/src/rust/api/rust_auto_opaque.dart, frb_example/pure_dart/lib/src/rust/api/rust_opaque.dart, frb_example/pure_dart/lib/src/rust/frb_generated.dart
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/1505
=> Fix linter errors when some extra linter rules are enabled

.github/workflows/ci.yaml, tools/frb_internal/bin/flutter_rust_bridge_internal.dart, tools/frb_internal/lib/src/makefile_dart/build.dart, tools/frb_internal/lib/src/makefile_dart/build.g.dart, tools/frb_internal/pubspec.lock, tools/frb_internal/pubspec.yaml
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/1571
=> Add CI for release mode and generate final artifacts

website/docs/manual/integrate/07-library/02-creating-libraries/02-flutter-wrapper.md, website/v1_mdbook/src/library/flutter_wrapper.md
=> Update doc about library lookup

frb_codegen/src/library/commands/cbindgen.rs, frb_codegen/src/library/internal/mod.rs, frb_dart/lib/src/ffigen_generated/intermediate/allo_isolate.h, frb_dart/lib/src/ffigen_generated/intermediate/frb_rust.h, frb_dart/lib/src/ffigen_generated/multi_package.dart, frb_rust/src/dart_opaque/mod.rs, frb_rust/src/dart_opaque/web.rs, frb_rust/src/generalized_isolate/mod.rs, frb_rust/src/misc/mod.rs, frb_rust/src/platform_types/mod.rs, frb_rust/src/platform_types/web.rs
=> Improve `frb_dart/ffigen_generated`

frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/wire_func.rs, frb_example/pure_dart/rust/src/api/event_listener.rs, frb_example/pure_dart/rust/src/api/method.rs, frb_example/pure_dart/rust/src/api/mirror.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/event_listener_twin_rust_async.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/event_listener_twin_rust_async_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/event_listener_twin_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/method_twin_rust_async.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/method_twin_rust_async_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/method_twin_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/method_twin_sync.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/method_twin_sync_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_rust_async.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_rust_async_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_sync.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/mirror_twin_sync_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/stream_misc_twin_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/stream_twin_rust_async.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/stream_twin_rust_async_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/stream_twin_sse.rs, frb_example/pure_dart/rust/src/api/stream.rs, frb_example/pure_dart/rust/src/api/stream_misc.rs, frb_rust/src/codec/mod.rs, frb_rust/src/for_generated/boilerplate.rs, frb_rust/src/handler/handler.rs, frb_rust/src/handler/implementation/executor.rs, frb_rust/src/rust2dart/context.rs, frb_rust/src/rust2dart/stream_sink.rs, website/docs/guides/miscellaneous/upgrade/v2.md
=> Automatically close streams when it is dropped

frb_codegen/src/library/codegen/parser/attribute_parser.rs
=> Add test when parsing non-existing attribute name

frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/wire_func.rs, frb_codegen/src/library/codegen/ir/ty/delegate.rs, frb_example/gallery/rust/src/frb_generated.io.rs, frb_example/gallery/rust/src/frb_generated.rs, frb_example/gallery/rust/src/frb_generated.web.rs, frb_example/pure_dart/rust/src/frb_generated.io.rs, frb_example/pure_dart/rust/src/frb_generated.rs, frb_example/pure_dart/rust/src/frb_generated.web.rs
=> Fix compile error when the user crate does not have anyhow as direct dependency

frb_rust/src/misc/user_utils.rs, frb_rust/src/misc/web_utils.rs
=> Let `setup_default_user_utils` setup logging in web

frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/wire_func.rs
=> Partially fix issue with thiserror error

.github/workflows/ci.yaml, website/src/components/FrbExampleGallery.tsx, website/src/css/custom.css
=> Fix website animation

frb_example/pure_dart/frb_generated.h, frb_example/pure_dart/lib/src/rust/api/misc_no_twin_example_a.dart, frb_example/pure_dart/lib/src/rust/frb_generated.dart, frb_example/pure_dart/lib/src/rust/frb_generated.io.dart, frb_example/pure_dart/lib/src/rust/frb_generated.web.dart, frb_example/pure_dart/rust/src/api/misc_no_twin_example_a.rs, frb_example/pure_dart/rust/src/api/misc_no_twin_example_b.rs, frb_example/pure_dart/rust/src/frb_generated.io.rs, frb_example/pure_dart/rust/src/frb_generated.rs, frb_example/pure_dart/rust/src/frb_generated.web.rs
=> Add test that one struct has multiple impl blocks in multiple files

.github/workflows/ci.yaml
=> Fix CI valgrind cannot be installed

frb_codegen/src/library/commands/flutter.rs
=> Improve hints when running create command

frb_example/pure_dart/rust/example_external_lib/src/lib.rs, frb_example/pure_dart/rust/src/api/mirror.rs, frb_rust/src/misc/into_into_dart.rs
=> Fix when using types in external crate and use HashMap to contain it (partial)

frb_codegen/assets/integration_template/REPLACE_ME_RUST_CRATE_DIR/src/frb_generated.rs, frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/codec/pde/entrypoint.rs, frb_example/dart_minimal/rust/src/frb_generated.rs, frb_example/deliberate_bad/rust/src/frb_generated.rs, frb_example/flutter_via_create/rust/src/frb_generated.rs, frb_example/flutter_via_integrate/rust/src/frb_generated.rs, frb_example/gallery/rust/src/frb_generated.rs, frb_example/pure_dart_pde/rust/src/frb_generated.rs
=> Improve comments for generated code

frb_example/pure_dart/test/isolate_test.dart, frb_example/pure_dart_pde/test/isolate_test.dart, website/docs/guides/miscellaneous/isolates.md, website/sidebars.js
=> Add tests and doc about multiple Dart Isolates

frb_rust/src/rust_opaque/mod.rs, website/docs/guides/miscellaneous/upgrade/v2.md
=> Add doc about movement of things like `StreamSink`

frb_rust/src/rust_opaque/mod.rs, website/docs/guides/types/arbitrary/rust-opaque.md
=> Fix generated code is breaking cargo test because of its doc-test contains a moved import

.github/workflows/ci.yaml, Cargo.lock, frb_codegen/assets/integration_template/REPLACE_ME_RUST_CRATE_DIR/Cargo.lock.template, frb_dart/pubspec.yaml, frb_example/dart_build_rs/rust/Cargo.lock, frb_example/dart_minimal/rust/Cargo.lock, frb_example/deliberate_bad/rust/Cargo.lock, frb_example/flutter_via_create/pubspec.lock, frb_example/flutter_via_create/rust/Cargo.lock, frb_example/flutter_via_integrate/pubspec.lock, frb_example/flutter_via_integrate/rust/Cargo.lock, frb_example/gallery/rust/Cargo.lock, frb_example/pure_dart/rust/Cargo.lock, frb_example/pure_dart_pde/rust/Cargo.lock, frb_rust/Cargo.toml
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/1734
=> Fix CI failure (though no real errors)

frb_example/gallery/lib/src/ignore_me/mandelbrot_related.dart
=> Improve demo UI when on small-screen devices

frb_codegen/src/binary/commands_parser.rs
=> Inform users when both config file and command line arguments are used

website/docs/guides/how-to/logging.md
=> Mention flutter_logger in doc

website/docs/guides/types/translatable/stream.md
Fixes #1755
- [inapplicable] New tests are added to ensure new features are working. Please refer to [this page](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip) to see how to add a test.
=> [docs] Fix import of `StreamSink`

frb_codegen/src/library/build_web/mod.rs, frb_codegen/src/library/commands/command_runner.rs
=> Fix build-web cannot find Dart program in some platforms

website/docs/guides/how-to/gitignore.md, website/docs/manual/troubleshooting.md, website/sidebars.js
=> Improve doc to explain what to be gitignored

frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/field.rs
=> Fix when non-enum + specify default value + dart_enums_style being true

website/docs/guides/how-to/cargo-workspaces.md, website/sidebars.js
Fixes #1810
- Add page about Cargo Workspaces to the documentation
=> Add page about Cargo Workspaces to the documentation

website/docs/manual/troubleshooting.md
https://github.com/fzyzcjy/flutter_rust_bridge/issues/1868
@fzyzcjy - adding in the documentation, for the help of others when they might require.
=> Updated documentation with direct access to Android context

.github/workflows/ci.yaml, frb_example/pure_dart/test/api/event_listener_test.dart, frb_example/pure_dart/test/api/pseudo_manual/event_listener_twin_rust_async_sse_test.dart, frb_example/pure_dart/test/api/pseudo_manual/event_listener_twin_rust_async_test.dart, frb_example/pure_dart/test/api/pseudo_manual/event_listener_twin_sse_test.dart, frb_example/pure_dart_pde/test/api/event_listener_test.dart, frb_example/pure_dart_pde/test/api/pseudo_manual/event_listener_twin_rust_async_test.dart
=> Fix Android CI failing without code change because it cannot create AVD

frb_rust/src/dart_api/dart_api.h, frb_rust/src/dart_api/dart_tools_api.h
=> Bump Dart SDK source

frb_rust/src/rust2dart/sender.rs
=> Improve hints when Flutter hot restarts with Streams

frb_codegen/src/library/codegen/generator/codec/sse/ty/delegate.rs, frb_example/gallery/rust/src/frb_generated.rs, frb_example/pure_dart_pde/rust/src/frb_generated.rs
=> Fix when users do not have explicit dependency on anyhow

frb_example/dart_minimal/lib/src/rust/api/minimal.dart, frb_example/dart_minimal/rust/src/api/minimal.rs
Reverts fzyzcjy/flutter_rust_bridge#1986
=> Revert "Support code block in `dart_code`"

frb_dart/lib/src/cli/build_web/entrypoint.dart, frb_dart/lib/src/cli/build_web/entrypoint.g.dart, frb_dart/lib/src/cli/build_web/executor.dart, frb_utils/lib/src/dart_web_test_utils/run_test.dart, website/docs/generated/_frb-codegen-command-build-web.mdx
Close https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1971#discussioncomment-9558981
=> Support overriding environment variable for build-web

website/docs/guides/functions/ignoring.md
=> Explain ignoring functions using pub modifier more clearly

website/docs/manual/miscellaneous/02-web-cross-origin.md, website/docs/quickstart.md
=> Update doc to reflect latest approach to run on Web

frb_codegen/src/library/codegen/generator/api_dart/spec_generator/info.rs, frb_example/pure_dart/frb_generated.h, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/basic_list.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/basic_list_twin_rust_async.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/basic_list_twin_rust_async_sse.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/basic_list_twin_sse.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/basic_list_twin_sync.dart, frb_example/pure_dart/lib/src/rust/api/pseudo_manual/basic_list_twin_sync_sse.dart, frb_example/pure_dart/lib/src/rust/frb_generated.web.dart, frb_example/pure_dart/rust/src/api/pseudo_manual/basic_list.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/basic_list_twin_rust_async.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/basic_list_twin_rust_async_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/basic_list_twin_sse.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/basic_list_twin_sync.rs, frb_example/pure_dart/rust/src/api/pseudo_manual/basic_list_twin_sync_sse.rs, frb_example/pure_dart/rust/src/frb_generated.io.rs, frb_example/pure_dart/rust/src/frb_generated.web.rs, frb_example/pure_dart/test/api/pseudo_manual/basic_list_test.dart, frb_example/pure_dart/test/api/pseudo_manual/basic_list_twin_rust_async_sse_test.dart, frb_example/pure_dart/test/api/pseudo_manual/basic_list_twin_rust_async_test.dart, frb_example/pure_dart/test/api/pseudo_manual/basic_list_twin_sse_test.dart, frb_example/pure_dart/test/api/pseudo_manual/basic_list_twin_sync_sse_test.dart, frb_example/pure_dart/test/api/pseudo_manual/basic_list_twin_sync_test.dart, frb_example/pure_dart_pde/rust/src/api/pseudo_manual/basic_list.rs, frb_example/pure_dart_pde/rust/src/api/pseudo_manual/basic_list_twin_rust_async.rs, frb_example/pure_dart_pde/rust/src/api/pseudo_manual/basic_list_twin_sync.rs, frb_example/pure_dart_pde/test/api/pseudo_manual/basic_list_test.dart, frb_example/pure_dart_pde/test/api/pseudo_manual/basic_list_twin_rust_async_test.dart, frb_example/pure_dart_pde/test/api/pseudo_manual/basic_list_twin_sync_test.dart, tools/frb_internal/lib/src/frb_example_pure_dart_generator/basic_type_infos.dart
=> Enhance `usize` and `isize`

frb_codegen/src/library/codegen/ir/hir/hierarchical/function.rs, frb_codegen/src/library/codegen/ir/hir/hierarchical/module.rs, frb_codegen/src/library/codegen/ir/hir/hierarchical/struct_or_enum.rs, frb_codegen/src/library/codegen/parser/hir/flat/mod.rs, frb_codegen/src/library/codegen/parser/hir/hierarchical/crates.rs, frb_codegen/src/library/codegen/parser/hir/hierarchical/mod.rs, frb_codegen/src/library/codegen/parser/hir/hierarchical/module.rs, frb_codegen/src/library/codegen/parser/hir/hierarchical/pub_use.rs, frb_codegen/src/library/codegen/parser/mod.rs, frb_codegen/test_fixtures/library/codegen/parser/mod/generics/expect_hir_hierarchical.json, frb_codegen/test_fixtures/library/codegen/parser/mod/methods/expect_hir_hierarchical.json, frb_codegen/test_fixtures/library/codegen/parser/mod/multi_input_file/expect_hir_hierarchical.json, frb_codegen/test_fixtures/library/codegen/parser/mod/non_qualified_names/expect_hir_hierarchical.json, frb_codegen/test_fixtures/library/codegen/parser/mod/qualified_names/expect_hir_hierarchical.json, frb_codegen/test_fixtures/library/codegen/parser/mod/simple/expect_hir_hierarchical.json, frb_codegen/test_fixtures/library/codegen/parser/mod/unused_struct_enum/expect_hir_hierarchical.json, frb_codegen/test_fixtures/library/codegen/parser/mod/use_type_in_another_file/expect_hir_hierarchical.json
=> Support syntax of `pub use something::*`

frb_codegen/src/library/codegen/generator/api_dart/text_generator.rs, frb_codegen/src/library/codegen/misc.rs, frb_codegen/src/library/utils/namespace.rs
=> Improve Dart output directory of third party crates

frb_codegen/src/library/codegen/parser/hir/hierarchical/third_party_override_transformer.rs, frb_codegen/src/library/codegen/parser/mir/type_parser/external_impl.rs, frb_macros/src/lib.rs
=> Support overriding things in third party crate (part 2)

frb_codegen/src/library/codegen/generator/api_dart/misc.rs, frb_codegen/src/library/codegen/generator/api_dart/mod.rs, frb_codegen/src/library/codegen/generator/api_dart/spec_generator/misc.rs, frb_codegen/src/library/codegen/generator/api_dart/text_generator.rs, frb_codegen/src/library/utils/namespace.rs
=> Improve Dart import generation

frb_codegen/src/library/codegen/ir/hir/flat/function.rs, frb_codegen/src/library/codegen/ir/hir/misc/generation_source.rs, frb_codegen/src/library/codegen/ir/mir/func.rs, frb_codegen/src/library/codegen/parser/hir/flat/mod.rs, frb_codegen/src/library/codegen/parser/hir/flat/transformer/function_frb_override_transformer.rs, frb_codegen/src/library/codegen/parser/hir/flat/transformer/merge_duplicate_transformer/function_frb_override_merger.rs, frb_codegen/src/library/codegen/parser/hir/flat/transformer/merge_duplicate_transformer/mod.rs, frb_codegen/src/library/codegen/parser/hir/flat/transformer/merge_duplicate_transformer/override_merger.rs, frb_codegen/src/library/codegen/parser/hir/flat/transformer/merge_duplicate_transformer/third_party_override_merger.rs, frb_codegen/src/library/codegen/parser/hir/flat/transformer/mod.rs, frb_codegen/src/library/codegen/parser/mir/auto_accessor_parser/field.rs, frb_codegen/src/library/codegen/parser/mir/function_parser/mod.rs, frb_codegen/src/library/codegen/parser/mir/mod.rs, frb_codegen/src/library/utils/syn_utils.rs, frb_codegen/test_fixtures/library/codegen/parser/mod/generics/expect_mir.json, frb_codegen/test_fixtures/library/codegen/parser/mod/methods/expect_mir.json, frb_codegen/test_fixtures/library/codegen/parser/mod/multi_input_file/expect_mir.json, frb_codegen/test_fixtures/library/codegen/parser/mod/non_qualified_names/expect_mir.json, frb_codegen/test_fixtures/library/codegen/parser/mod/qualified_names/expect_mir.json, frb_codegen/test_fixtures/library/codegen/parser/mod/simple/expect_mir.json, frb_codegen/test_fixtures/library/codegen/parser/mod/use_type_in_another_file/expect_mir.json, frb_example/integrate_third_party/lib/src/rust/third_party/web_audio_api/context.dart
=> Refactor override_priority and refine_namespace

frb_codegen/src/library/utils/logs.rs
=> Do not create empty logs directory when not in verbose mode

frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/misc.rs, frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/ty/enumeration.rs, frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/ty/rust_opaque.rs, frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/ty/structure.rs, frb_codegen/src/library/codegen/generator/wire/dart/spec_generator/output_code.rs, frb_codegen/src/library/codegen/ir/mir/pack.rs, frb_codegen/src/library/codegen/parser/mir/parser/ty/enum_or_struct.rs, frb_codegen/src/library/codegen/parser/mir/parser/ty/enumeration.rs, frb_codegen/src/library/codegen/parser/mir/parser/ty/mod.rs, frb_codegen/src/library/codegen/parser/mir/parser/ty/structure.rs, frb_codegen/src/library/utils/basic_code/mod.rs, frb_codegen/src/library/utils/basic_code/parser.rs, frb_example/dart_minimal/rust/src/api/minimal.rs, frb_example/pure_dart/lib/src/rust/api/dart_code.dart, frb_example/pure_dart/rust/src/api/dart_code.rs, frb_example/pure_dart_pde/lib/src/rust/api/dart_code.dart, frb_example/pure_dart_pde/rust/src/api/dart_code.rs, website/docs/guides/miscellaneous/dart-code.md
=> Support import statements in `dart_code`

frb_codegen/src/binary/commands.rs, frb_codegen/src/binary/commands_parser.rs, frb_codegen/src/library/codegen/config/config.rs, frb_codegen/src/library/codegen/config/internal_config_parser/generator_parser.rs, frb_codegen/src/library/codegen/generator/wire/rust/internal_config.rs, frb_codegen/src/library/codegen/generator/wire/rust/spec_generator/misc/mod.rs, frb_codegen/test_fixtures/library/codegen/config/internal_config_parser/single_rust_input/expect_output.json, frb_codegen/test_fixtures/library/codegen/config/internal_config_parser/wildcard_rust_input/expect_output.json, frb_codegen/test_fixtures/library/codegen/generator/api_dart/mod/simple/flutter_rust_bridge.yaml, frb_example/dart_minimal/flutter_rust_bridge.yaml, frb_example/pure_dart/flutter_rust_bridge.yaml, frb_example/pure_dart/rust/src/frb_generated.io.rs, frb_example/pure_dart/rust/src/frb_generated.web.rs, frb_example/pure_dart_pde/flutter_rust_bridge.yaml, frb_example/pure_dart_pde/rust/src/frb_generated.io.rs, frb_example/pure_dart_pde/rust/src/frb_generated.rs, frb_example/pure_dart_pde/rust/src/frb_generated.web.rs, website/docs/generated/_frb-codegen-command-generate.mdx
=> Support adding arbitrary code in generated Rust file via `rust_preamble` config

frb_codegen/assets/integration_template/REPLACE_ME_RUST_CRATE_DIR/src/api/mod.rs, frb_codegen/assets/integration_template/REPLACE_ME_RUST_CRATE_DIR/src/lib.rs, frb_example/flutter_via_create/rust/src/api/mod.rs, frb_example/flutter_via_create/rust/src/lib.rs, frb_example/flutter_via_integrate/rust/src/api/mod.rs, frb_example/flutter_via_integrate/rust/src/lib.rs
=> Update default template comments

website/docs/guides/custom/attributes.md, website/docs/guides/misc-features/ignoring.md, website/docs/guides/third-party/automatic/third-party-modifiable.md
=> Improve documentations

.github/workflows/post_release.yaml, README.md, website/docs/guides/custom/codegen.md, website/docs/guides/miscellaneous/upgrade/regular.md, website/docs/guides/miscellaneous/whats-new.md, website/docs/index.md, website/docs/quickstart.md
=> Update doc for 2.0.0 version number

.github/workflows/post_release.yaml, website/docs/quickstart.md
Thanks @Desdaemon in https://github.com/Desdaemon/homebrew-repo/issues/121
=> Re-enable scoop and homebrew installation approaches

frb_codegen/src/library/codegen/parser/mir/parser/attribute.rs, website/docs/guides/custom/attributes/comments.md, website/docs/guides/custom/attributes/full-list.md, website/docs/guides/custom/attributes/index.md, website/docs/guides/custom/codegen/full-list.md, website/docs/guides/custom/codegen/index.md, website/docs/guides/custom/codegen/inputs.md, website/docs/guides/custom/dart/constructors.md, website/docs/guides/custom/dart/index.md, website/docs/guides/custom/rust/feature-flags.md, website/docs/guides/custom/rust/handlers.md, website/docs/guides/custom/rust/index.md, website/docs/guides/custom/rust/wasm-init.md, website/sidebars.js
=> Add documentations of full list of attributes

.github/workflows/ci.yaml
=> Upgrade GitHub Actions CI macos version

frb_dart/pubspec.yaml, frb_example/flutter_package/example/pubspec.lock, frb_example/flutter_via_create/pubspec.lock, frb_example/flutter_via_integrate/pubspec.lock
=> Fix CI linter by supporting dependency `web >= 1.0.0`

frb_dart/test/entrypoint_test.dart
=> test: add unit test for 2248

website/docs/guides/misc-features/rust-ui-utilities.md, website/sidebars.js
=> Add doc about `#[frb(ui_state)]` and `#[frb(ui_mutation)]`

website/docs/guides/how-to/stack-trace.md
=> Update doc mentioning Rust stack trace on Windows

website/docs/guides/types/translatable/stream.md
It was unclear to me how to use frb's Streams. This small changes clarify what a user has to do, and what happens automagically :)
=> Minimaly clarifies how to use streams

Cargo.lock, Cargo.toml, frb_example/dart_build_rs/rust/Cargo.lock, frb_example/dart_minimal/rust/Cargo.lock, frb_example/deliberate_bad/rust/Cargo.lock, frb_example/flutter_package/rust/Cargo.lock, frb_example/flutter_via_create/rust/Cargo.lock, frb_example/flutter_via_integrate/rust/Cargo.lock, frb_example/gallery/rust/Cargo.lock, frb_example/integrate_third_party/rust/Cargo.lock, frb_example/pure_dart/rust/Cargo.lock, frb_example/pure_dart_pde/rust/Cargo.lock, frb_example/rust_ui_counter/Cargo.lock, frb_example/rust_ui_todo_list/Cargo.lock
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/2358
=> Upgrade allo-isolate

Cargo.lock, frb_codegen/Cargo.toml
=> Update syn as a transitive dependency to version 2.0

.all-contributors-custom.yaml, Cargo.lock, README.md, frb_codegen/Cargo.toml, frb_example/dart_build_rs/rust/Cargo.lock, website/docs/index.md
Continue on #2371, only need to bump some lock files
Close #2368
=> Update syn as a transitive dependency to version 2.0 (Continued)

frb_codegen/src/library/internal/frb_rust_source_code.rs, frb_dart/lib/src/ffigen_generated/intermediate/frb_rust.h, frb_dart/lib/src/ffigen_generated/multi_package.dart, frb_dart/lib/src/generalized_frb_rust_binding/_io.dart, frb_dart/lib/src/generalized_frb_rust_binding/_web.dart, frb_rust/src/dart_opaque/dart2rust.rs, frb_rust/src/dart_opaque/non_clone.rs, frb_rust/src/dart_opaque/rust2dart.rs, frb_rust/src/ffi_binding/io.rs, frb_rust/src/ffi_binding/mod.rs, frb_rust/src/internal_generated/mod.rs
=> Clear up symbols

website/docs/guides/how-to/build-release.md, website/sidebars.js
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/2417
=> Add doc about how to build

website/docs/manual/miscellaneous/02-web-cross-origin.md
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/2407
=> Update doc about `flutter drive` in web with cross origin

.github/workflows/ci.yaml
=> Upgrade iOS Simulator version in CI

frb_dart/lib/src/exceptions.dart, frb_dart/lib/src/wasm_module/_web.dart, frb_dart/test/exceptions_test.dart, website/docs/manual/miscellaneous/02-web-cross-origin.md
=> Replaced WASM header exception with warning & updated documentation for cross-origin isolation

frb_codegen/src/library/build_web/mod.rs
Fix call ```flutter_rust_bridge_codegen build-web``` with fvm support.
=> Fix call build-web with fvm support

frb_example/flutter_package/example/pubspec.lock, frb_example/flutter_via_create/pubspec.lock, frb_example/flutter_via_integrate/pubspec.lock, frb_example/gallery/pubspec.lock, frb_example/integrate_third_party/pubspec.lock, frb_example/rust_ui_counter/ui/pubspec.lock, frb_example/rust_ui_todo_list/ui/pubspec.lock
=> Bump pubspec.lock

frb_codegen/Cargo.toml, frb_codegen/src/library/commands/cbindgen.rs
=> chore: downgrade rust version in frb_codegen

frb_codegen/src/library/codegen/generator/api_dart/spec_generator/class/ty/enumeration_complex.rs, frb_codegen/src/library/codegen/generator/api_dart/text_generator.rs
=> Add freezed JSON serialization

frb_example/flutter_package/example/windows/runner/Runner.rc, frb_example/flutter_via_create/windows/runner/Runner.rc, frb_example/flutter_via_integrate/windows/runner/Runner.rc, frb_example/integrate_third_party/windows/runner/Runner.rc, frb_example/rust_ui_counter/ui/windows/runner/Runner.rc, frb_example/rust_ui_todo_list/ui/windows/runner/Runner.rc, website/docs/guides/how-to/cargo-workspaces.md
=> Minor change doc

frb_codegen/src/library/commands/cargo_expand/real.rs, frb_codegen/src/library/commands/command_runner.rs, frb_codegen/src/library/commands/dart_build_runner.rs, frb_codegen/src/library/commands/ffigen.rs, frb_codegen/src/library/commands/fvm.rs, frb_example/dart_minimal/rust/src/api/minimal.rs, website/docs/manual/troubleshooting.md
=> Do not warn when fvm not found or for unexpected condition name

website/docs/guides/traits/trait-objects.md
I think this is what was meant?
=> Fix example trait-objects.md

website/docs/guides/how-to/ndk-init.md, website/docs/guides/how-to/transferable-typed-data.md, website/docs/guides/miscellaneous/compatibility.md, website/docs/guides/types/arbitrary/rust-auto-opaque/override-defaults.md, website/docs/manual/troubleshooting.md, website/sidebars.js
Fix #2479
Fix #2520
Fix #2466
Fix #2467
Fix #2530
Fix #2531
=> Update docs 

frb_dart/lib/src/wasm_module/_web.dart, frb_dart/pubspec.yaml
Temporarily fix (so don't close) #2384 
=> Fix web cache issues by appending version query parameter to wasm/js requests

website/docs/guides/types/arbitrary/dart-dynamic.md
- typo in docs `esacpe ` -> `escape`
=> typo in docs `esacpe ` -> `escape`

website/docs/guides/how-to/nix.md, website/sidebars.js
=> Add doc about Nixpkgs/NixOS

website/docs/guides/third-party/manual/external-types.md
Use traits in external third-party packages
Capture the summary of using third-party package traits discussed here at [https://github.com/fzyzcjy/flutter_rust_bridge/discussions/2590](https://github.com/fzyzcjy/flutter_rust_bridge/discussions/2590)
=> Update external-types.md - Use traits in external third-party packages

frb_codegen/src/binary/commands.rs, frb_codegen/src/binary/commands_parser.rs, frb_codegen/src/library/codegen/config/config.rs, frb_codegen/src/library/codegen/config/internal_config_parser/mod.rs, frb_codegen/src/library/codegen/polisher/auto_upgrade.rs, frb_codegen/src/library/codegen/polisher/mod.rs, website/docs/generated/_frb-codegen-command-generate.mdx
=> Add `auto_upgrade_dependency` option

.github/PULL_REQUEST_TEMPLATE.md
Fixes #the-issue-number-here
* Run tests: `./frb_internal test-dart-native --package frb_example/dart_minimal`
=> Tiny fix PR template

frb_codegen/src/library/codegen/generator/wire/dart/spec_generator/codec/dco/decoder/ty/primitive.rs, frb_dart/lib/src/manual_impl/_io.dart, frb_dart/lib/src/manual_impl/_web.dart, frb_dart/lib/src/platform_utils/_web.dart
Fix for strict-casts lint## Changes
Fixes #the-issue-number-here
=> Fix for strict-casts lint (continued)

.github/workflows/ci.yaml
=> feat: upgrade github ci to ubuntu 24.04

frb_rust/src/dart_api/dart_api.h, frb_rust/src/dart_api/dart_api_dl.h, frb_rust/src/dart_api/dart_version.h
=> Upgrade Dart API Headers

.gitignore, analysis_options.yaml, melos.yaml, pubspec.yaml
Integrating with Melos to help speed up bootstrapping the repo.
=> ✨ Add melos

.github/workflows/ci.yaml, .github/workflows/post_release.yaml, website/docs/manual/integrate/07-library/04-ci.md, website/v1_mdbook/src/library/ci.md
...to keep the setup flow clean and up-to-date.
=> 👷 Use `flutter-actions/setup-flutter` instead

website/docs/guides/misc-features/preambles.md, website/docs/guides/types/translatable/detailed/tuple.md, website/docs/guides/types/translatable/detailed/vec.md
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/2778
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/2777
Close https://github.com/fzyzcjy/flutter_rust_bridge/issues/2781
=> Several update to docs

.github/workflows/ci.yaml, tools/frb_internal/lib/src/makefile_dart/test.dart
=> Minor fix CI

frb_codegen/src/library/codegen/polisher/auto_upgrade.rs
=> Check for target dependencies when auto upgrading in codegen

.github/workflows/ci.yaml, .github/workflows/post_release.yaml, .github/workflows/release.yaml, .github/workflows/remove_labels.yml, .github/workflows/stale.yml
This PR should fix #2873. I updated all used action's versions to the latest stable versions, taking into account breaking changes (of which I found actually none).
=> Update actions versions of all workflows
